myFunction([
{
"display": "01",
"titulo": "Sora no Otoshimono",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRlV6VEhwQmRrMUVUVE5NZWxVeVRtazRkMDFFVFROT1ZGa3lUMFJGTTB4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRlV6VEhwQmRrMUVUVE5NZWxVeVRtazRkMDFFVFROT1ZGa3lUMFJGTTB4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "Sora no Otoshimono",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy81NjYvMDAzNzU2NjgzNC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy81NjYvMDAzNzU2NjgzNC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

{
"display": "06",
"titulo": "Sora no Otoshimono",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjYvMC8wMzcvNTY2LzAwMzc1NjY3MDEubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjYvMC8wMzcvNTY2LzAwMzc1NjY3MDEubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "07",
"titulo": "Sora no Otoshimono",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWM1ZERk5OR1F3ZURaUldIQlBaVlJuZUZSdGNGcGthekZGVVZod1QyVnNWWGxVYlhCdVRVVXhjRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUlhhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWM1ZERk5OR1F3ZURaUldIQlBaVlJuZUZSdGNGcGthekZGVVZod1QyVnNWWGxVYlhCdVRVVXhjRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUlhhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "08",
"titulo": "Sora no Otoshimono",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFWlBZV3hzTWxSVlVrSmxhelUyVmxSS1QyRnNiRFpVYldzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFWlBZV3hzTWxSVlVrSmxhelUyVmxSS1QyRnNiRFpVYldzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "09",
"titulo": "Sora no Otoshimono",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUmxVeFZFaHdRbVJyTVVWVVZFNU5aV3hWZVZSdGF6UmtNREZGVkZST1QxWkdhM2xVYlhCdVRWVjRkRTFZWkU5U1JHeDJXV3BPVDAxR1FsaGhSRXBwVmtWVmVsUlZaR3BrVjFKSlZsaFdhMU5HYXprPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUmxVeFZFaHdRbVJyTVVWVVZFNU5aV3hWZVZSdGF6UmtNREZGVkZST1QxWkdhM2xVYlhCdVRWVjRkRTFZWkU5U1JHeDJXV3BPVDAxR1FsaGhSRXBwVmtWVmVsUlZaR3BrVjFKSlZsaFdhMU5HYXprPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

{
"display": "11",
"titulo": "Sora no Otoshimono",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFWlBZV3hzTWxSVlVrSmxhelUyVmxSS1QyRnRUalZVVjJzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFWlBZV3hzTWxSVlVrSmxhelUyVmxSS1QyRnRUalZVVjJzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "12",
"titulo": "Sora no Otoshimono",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVFl2TUM4d016Y3ZOVFkyTHpBd016YzFOalkxTnprdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVFl2TUM4d016Y3ZOVFkyTHpBd016YzFOalkxTnprdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

{
"display": "14",
"titulo": "Sora no Otoshimono",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRbEJWZW1nelZFaHdRbVZyTlRWUFJFWlBZV3hzTWxSVlVrSmxhelUyVmxSS1QyRnNiRE5VYkUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRbEJWZW1nelZFaHdRbVZyTlRWUFJFWlBZV3hzTWxSVlVrSmxhelUyVmxSS1QyRnNiRE5VYkUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

])