myFunction([
{
"display": "01",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjQvMC8wMzcvNTgxLzAwMzc1ODEwODYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjQvMC8wMzcvNTgxLzAwMzc1ODEwODYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "02",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFWlFVa1ZXTWxSVlVrSmxhelUyVmxSU1RsWkZWak5VYldzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFWlFVa1ZXTWxSVlVrSmxhelUyVmxSU1RsWkZWak5VYldzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "03",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjUvMC8wMzcvNTgxLzAwMzc1ODExMDcubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjUvMC8wMzcvNTgxLzAwMzc1ODExMDcubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "04",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE0Ny8wLzAzNy81ODEvMDAzNzU4MTEyNS5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE0Ny8wLzAzNy81ODEvMDAzNzU4MTEyNS5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "05",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFWlFVa2RrTWxSVlVrSmxhelUyVmxSU1VGSkZSVEZVVlUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFWlFVa2RrTWxSVlVrSmxhelUyVmxSU1VGSkZSVEZVVlUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "06",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTVSZW1nelZFaHdRbVZyTlRWUFJFWlFWa1pXTWxSVlVrSmxhelUyVmxSV1QxWkdWWGxVYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTVSZW1nelZFaHdRbVZyTlRWUFJFWlFWa1pXTWxSVlVrSmxhelUyVmxSV1QxWkdWWGxVYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "07",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTgvMC8wMzcvNjAyLzAwMzc2MDI4NjgubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTgvMC8wMzcvNjAyLzAwMzc2MDI4NjgubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "08",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyOC8wLzAzNy82MTAvMDAzNzYxMDM3NC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyOC8wLzAzNy82MTAvMDAzNzYxMDM3NC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "09",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NS8wLzAzNy82MTYvMDAzNzYxNjMxOC5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NS8wLzAzNy82MTYvMDAzNzYxNjMxOC5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "10",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkVZeVZGVk5OR1F3TVRaWk0xcFBZV3RzTlZSSWNFSmtNREUyV1hwS1RtRnJiRFZVYkZKT1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkVZeVZGVk5OR1F3TVRaWk0xcFBZV3RzTlZSSWNFSmtNREUyV1hwS1RtRnJiRFZVYkZKT1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "11",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTkvMC8wMzcvNjI5LzAwMzc2MjkxMzgubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTkvMC8wMzcvNjI5LzAwMzc2MjkxMzgubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "12",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREpOZWxWMlRVUkJlazU2V1hwT1ZFMDFUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREpOZWxWMlRVUkJlazU2V1hwT1ZFMDFUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
{
"display": "13",
"titulo": "Kobayashi-san Chi no Maid Dragon",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFcFBVa1ZzTWxSVlVrSmxhelUyVjFSQ1RtRnJiRFpVV0dzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFcFBVa1ZzTWxSVlVrSmxhelUyVjFSQ1RtRnJiRFpVV0dzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.jpg'",
},
])