myFunction([
{
"display": "Especial",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDczLzAvMDM3LzQ1MC8wMDM3NDUwMzgzLm1wND9ob3N0PWh2bTE3MGcudHUudHYrWg=='",
"desc": "aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDczLzAvMDM3LzQ1MC8wMDM3NDUwMzgzLm1wND9ob3N0PWh2bTE3MGcudHUudHYrWg==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "131",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmFUVnBlRFZ2ZW01ek5qVTFNM2c1TDBRd01EWXhMVEV6TVM1dGNEUT0rRw==&vm=yes'",
"desc": "YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmFUVnBlRFZ2ZW01ek5qVTFNM2c1TDBRd01EWXhMVEV6TVM1dGNEUT0rRw==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "130",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmFYRnVOV0ozTlRCbVpqTnZhR0V5TDBRd01EWXhMVEV6TUM1dGNEUT0rRw==&vm=yes'",
"desc": "YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmFYRnVOV0ozTlRCbVpqTnZhR0V5TDBRd01EWXhMVEV6TUM1dGNEUT0rRw==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "129",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTTJRelpIazFkRnBYVW5CWlYxcHdZMjFWZFZreU9YUk1NbHB3WWtkVmRrOUViR2hoYlVVeVpIcGFORmt6YkRaUFJHdzJUREJSZDAxRVdYaE1WRVY1VDFNMWRHTkVVVDA9K1Q=&vm=yes'",
"desc": "WVVoU01HTkViM1pNTTJRelpIazFkRnBYVW5CWlYxcHdZMjFWZFZreU9YUk1NbHB3WWtkVmRrOUViR2hoYlVVeVpIcGFORmt6YkRaUFJHdzJUREJSZDAxRVdYaE1WRVY1VDFNMWRHTkVVVDA9K1Q=&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "128",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdlltZDFkV2h1Y1c5amJYazROWEpvTDBRd01EWXhMVEV5T0M1dGNEUT0rRw==&vm=yes'",
"desc": "YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdlltZDFkV2h1Y1c5amJYazROWEpvTDBRd01EWXhMVEV5T0M1dGNEUT0rRw==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "127",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmIzaHRZbmMwY1RjMmFHdDFiVEpuTDBRd01EWXhMVEV5Tnk1dGNEUT0rRw==&vm=yes'",
"desc": "YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmIzaHRZbmMwY1RjMmFHdDFiVEpuTDBRd01EWXhMVEV5Tnk1dGNEUT0rRw==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "126",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvZjFraTRqY2t4NXV5aDZ5L0QwMDYxLTEyNi5tcDQrWg==&vm=yes'",
"desc": "aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvZjFraTRqY2t4NXV5aDZ5L0QwMDYxLTEyNi5tcDQrWg==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "125",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmJHOXRNVGt6WkhRMmRqTnhPR0pyTDBRd01EWXhMVEV5TlM1dGNEUT0rRw==&vm=yes'",
"desc": "YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmJHOXRNVGt6WkhRMmRqTnhPR0pyTDBRd01EWXhMVEV5TlM1dGNEUT0rRw==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "124",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvNzJxOXhtdTFmaWRqbW16L0QwMDYxLTEyNC5tcDQrWg==&vm=yes'",
"desc": "aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvNzJxOXhtdTFmaWRqbW16L0QwMDYxLTEyNC5tcDQrWg==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "123",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvNzJxOXhtdTFmaWRqbW16L0QwMDYxLTEyNC5tcDQrWg==&vm=yes'",
"desc": "aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvNzJxOXhtdTFmaWRqbW16L0QwMDYxLTEyNC5tcDQrWg==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "122",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdk9HTnRhR2R1TkRVM2NXazNlamRqTDBRd01EWXhMVEV5TWk1dGNEUT0rRw==&vm=yes'",
"desc": "YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdk9HTnRhR2R1TkRVM2NXazNlamRqTDBRd01EWXhMVEV5TWk1dGNEUT0rRw==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "121",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTTJRelpIazFkRnBYVW5CWlYxcHdZMjFWZFZreU9YUk1NbHB3WWtkVmRsbHRUVEJhV0VKc1ducHNhMkp0VW0xTk1rVTBUREJSZDAxRVdYaE1WRVY1VFZNMWRHTkVVVDA9K1Q=&vm=yes'",
"desc": "WVVoU01HTkViM1pNTTJRelpIazFkRnBYVW5CWlYxcHdZMjFWZFZreU9YUk1NbHB3WWtkVmRsbHRUVEJhV0VKc1ducHNhMkp0VW0xTk1rVTBUREJSZDAxRVdYaE1WRVY1VFZNMWRHTkVVVDA9K1Q=&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "120",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUveHgycTJidjZ3MmM2YXJkL0QwMDYxLTEyMC5tcDQrWg==&vm=yes'",
"desc": "aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUveHgycTJidjZ3MmM2YXJkL0QwMDYxLTEyMC5tcDQrWg==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "119",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvdmo3aGIxNmRjaGp6dHNnL0QwMDYxLTExOS5tcDQrWg==&vm=yes'",
"desc": "aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvdmo3aGIxNmRjaGp6dHNnL0QwMDYxLTExOS5tcDQrWg==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "118",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdk9HNDVaelk1YUhsaWFuZzRZWEZyTDBRd01EWXhMVEV4T0M1dGNEUT0rRw==&vm=yes'",
"desc": "YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdk9HNDVaelk1YUhsaWFuZzRZWEZyTDBRd01EWXhMVEV4T0M1dGNEUT0rRw==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "117",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUveGR6aDllYXNneGRkcDF4L0QwMDYxLTExNy5tcDQrWg==&vm=yes'",
"desc": "aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUveGR6aDllYXNneGRkcDF4L0QwMDYxLTExNy5tcDQrWg==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "116",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRUSlJlbHBJYXpGa1JuQllWVzVDV2xZeGNIZFpNakZXWkZacmVVOVlVazFOYkhCM1dXdGtWbVJzYjNsWGJXeG9WMFUxTVZwV2FGZGhWVFUyVVZoc1RsTkZTbmRVUkVKU1pEQXhSVmRZYUUxV1JWWTBWRzFyTVdSSFRrVlZWREE5K1Y=&vm=yes'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRUSlJlbHBJYXpGa1JuQllWVzVDV2xZeGNIZFpNakZXWkZacmVVOVlVazFOYkhCM1dXdGtWbVJzYjNsWGJXeG9WMFUxTVZwV2FGZGhWVFUyVVZoc1RsTkZTbmRVUkVKU1pEQXhSVmRZYUUxV1JWWTBWRzFyTVdSSFRrVlZWREE5K1Y=&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "115",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTTJRelpIazFkRnBYVW5CWlYxcHdZMjFWZFZreU9YUk1NbHB3WWtkVmRtVlhhSGxhU0ZKeFRucGtibUp0ZUcxTmJVWnhUREJSZDAxRVdYaE1WRVY0VGxNMWRHTkVVVDA9K1Q=&vm=yes'",
"desc": "WVVoU01HTkViM1pNTTJRelpIazFkRnBYVW5CWlYxcHdZMjFWZFZreU9YUk1NbHB3WWtkVmRtVlhhSGxhU0ZKeFRucGtibUp0ZUcxTmJVWnhUREJSZDAxRVdYaE1WRVY0VGxNMWRHTkVVVDA9K1Q=&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "114",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvaTZnMHdveDJiM2Z1ZjEzL0QwMDYxLTExNC5tcDQrWg==&vm=yes'",
"desc": "aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvaTZnMHdveDJiM2Z1ZjEzL0QwMDYxLTExNC5tcDQrWg==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "113",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvd3EzY3E2bzB0OTlwYjJxL0QwMDYxLTExMy5tcDQrWg==&vm=yes'",
"desc": "aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvd3EzY3E2bzB0OTlwYjJxL0QwMDYxLTExMy5tcDQrWg==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "112",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdk5tOWpOVGR6YnpCbk5IQmliSEJqTDBRd01EWXhMVEV4TWk1dGNEUT0rRw==&vm=yes'",
"desc": "YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdk5tOWpOVGR6YnpCbk5IQmliSEJqTDBRd01EWXhMVEV4TWk1dGNEUT0rRw==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "111",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmQyVTBlRGh4ZUhNMmMzUXpiV1V3TDBRd01EWXhMVEV4TVM1dGNEUT0rRw==&vm=yes'",
"desc": "YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmQyVTBlRGh4ZUhNMmMzUXpiV1V3TDBRd01EWXhMVEV4TVM1dGNEUT0rRw==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "110",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRUSlJlbHBJYXpGa1JuQllWVzVDV2xZeGNIZFpNakZXWkZacmVVOVlVazFOYkhCM1dXdGtWbVJyTkhsUFNHaE9WakpOTVZkdE1VOWtiVkp4Vm01V1QyRnJXVEpVUkVKU1pEQXhSVmRZYUUxV1JWWTBWRlZOTVdSSFRrVlZWREE5K1Y=&vm=yes'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRUSlJlbHBJYXpGa1JuQllWVzVDV2xZeGNIZFpNakZXWkZacmVVOVlVazFOYkhCM1dXdGtWbVJyTkhsUFNHaE9WakpOTVZkdE1VOWtiVkp4Vm01V1QyRnJXVEpVUkVKU1pEQXhSVmRZYUUxV1JWWTBWRlZOTVdSSFRrVlZWREE5K1Y=&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "109",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvdGljaG9vb215NmdvbThsL0QwMDYxLTEwOS5tcDQrWg==&vm=yes'",
"desc": "aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvdGljaG9vb215NmdvbThsL0QwMDYxLTEwOS5tcDQrWg==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "108",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRUSlJlbHBJYXpGa1JuQllWVzVDV2xZeGNIZFpNakZXWkZacmVVOVlVazFOYkhCM1dXdGtWbVJ0VWpaVGJYaE9Wak5TY1ZsdGNHRk5NV3gxWWtob2FFMHlVbkZVUkVKU1pEQXhSVmRZYUUxV1JWWXpWREJOTVdSSFRrVlZWREE5K1Y=&vm=yes'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRUSlJlbHBJYXpGa1JuQllWVzVDV2xZeGNIZFpNakZXWkZacmVVOVlVazFOYkhCM1dXdGtWbVJ0VWpaVGJYaE9Wak5TY1ZsdGNHRk5NV3gxWWtob2FFMHlVbkZVUkVKU1pEQXhSVmRZYUUxV1JWWXpWREJOTVdSSFRrVlZWREE5K1Y=&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "107",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmFETmhZekV6WkdFM1lXbHRNM2MwTDBRd01EWXhMVEV3Tnk1dGNEUT0rRw==&vm=yes'",
"desc": "YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmFETmhZekV6WkdFM1lXbHRNM2MwTDBRd01EWXhMVEV3Tnk1dGNEUT0rRw==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "106",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTTJRelpIazFkRnBYVW5CWlYxcHdZMjFWZFZreU9YUk1NbHB3WWtkVmRrNHpXakZaYlhNMFRqSnJNMWw2YUdwbGFtaDZUREJSZDAxRVdYaE1WRVYzVG1rMWRHTkVVVDA9K1Q=&vm=yes'",
"desc": "WVVoU01HTkViM1pNTTJRelpIazFkRnBYVW5CWlYxcHdZMjFWZFZreU9YUk1NbHB3WWtkVmRrNHpXakZaYlhNMFRqSnJNMWw2YUdwbGFtaDZUREJSZDAxRVdYaE1WRVYzVG1rMWRHTkVVVDA9K1Q=&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "105",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTJ3eVZGVk5OR1F3TVRaWk0xcFBaVzEwTlZSSWNFSmtNREUyV1hwT1VGWkZiRFpVYlhCR1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTJ3eVZGVk5OR1F3TVRaWk0xcFBaVzEwTlZSSWNFSmtNREUyV1hwT1VGWkZiRFpVYlhCR1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "104",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFNVFVa1pXTWxSVlVrSmxhelUyV1hwU1QxWkZNREJVVjJzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFNVFVa1pXTWxSVlVrSmxhelUyV1hwU1QxWkZNREJVVjJzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "103",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjMvMC8wMzcvNzc4LzAwMzc3NzgyODkubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjMvMC8wMzcvNzc4LzAwMzc3NzgyODkubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "102",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkd3eVZGVk5OR1F3TVRaWk0xcFBaVzFPTTFSSWNFSmtNREUyV1hwT1QyVnJSak5VYlhCS1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkd3eVZGVk5OR1F3TVRaWk0xcFBaVzFPTTFSSWNFSmtNREUyV1hwT1QyVnJSak5VYlhCS1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "101",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmJHWnJhbTA0WldkcVoyRm1jVFJ1TDBRd01EWXhMVEV3TVM1dGNEUT0rRw==&vm=yes'",
"desc": "YUhSMGNEb3ZMM2QzZHk1dFpXUnBZV1pwY21VdVkyOXRMMlpwYkdVdmJHWnJhbTA0WldkcVoyRm1jVFJ1TDBRd01EWXhMVEV3TVM1dGNEUT0rRw==&vm=yes",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

{
"display": "99",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPRE5PYWxWMlRVUkJlazU2WXpKT1ZFVXdUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPRE5PYWxWMlRVUkJlazU2WXpKT1ZFVXdUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},



{
"display": "97",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha2wyVFVNNGQwMTZZM1pPZWxsNlRIcEJkMDE2WXpOT2FrMHpUVVJSZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha2wyVFVNNGQwMTZZM1pPZWxsNlRIcEJkMDE2WXpOT2FrMHpUVVJSZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

{
"display": "95",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFNeTh3THpBek55ODNNVGN2TURBek56Y3hOelk0Tmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFNeTh3THpBek55ODNNVGN2TURBek56Y3hOelk0Tmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

{
"display": "93",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFcFFWa2RrTWxSVlVrSmxhelUyVjFSV1VGSkdSalpVVjJzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFcFFWa2RrTWxSVlVrSmxhelUyVjFSV1VGSkdSalpVVjJzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "92",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVV4VGtNNGQweDZRWHBPZVRneVQxUlJkazFFUVhwT2VsazFUa1JWZVUxRE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVV4VGtNNGQweDZRWHBPZVRneVQxUlJkazFFUVhwT2VsazFUa1JWZVUxRE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "90",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaRFl4THpBdk1ETTNMelkzT1M4d01ETTNOamM1TURVeExtMXdORDlvYjNOMFBXaDJiVEUzTUdjdWRIVXVkSFk9K0c='",
"desc": "YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaRFl4THpBdk1ETTNMelkzT1M4d01ETTNOamM1TURVeExtMXdORDlvYjNOMFBXaDJiVEUzTUdjdWRIVXVkSFk9K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "89",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaREUwTmk4d0x6QXpOeTgyTnpFdk1EQXpOelkzTVRRME9TNXRjRFEvYUc5emREMW9kakU0TWk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaREUwTmk4d0x6QXpOeTgyTnpFdk1EQXpOelkzTVRRME9TNXRjRFEvYUc5emREMW9kakU0TWk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "88",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREpPYWxWMlRVUkJlazU2V1RKT1ZHTjVUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREpPYWxWMlRVUkJlazU2V1RKT1ZHTjVUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "87",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZURjBWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZZMVZHeE5OR1F3ZURaUldIQlBaVlJuZVZSc1VtNWthekZGVVZod1QyVnNhM2hVTUZKS1RUQTFWRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUlhhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZURjBWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZZMVZHeE5OR1F3ZURaUldIQlBaVlJuZVZSc1VtNWthekZGVVZod1QyVnNhM2hVTUZKS1RUQTFWRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUlhhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "86",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjQvMC8wMzcvNjUxLzAwMzc2NTE2OTYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjQvMC8wMzcvNjUxLzAwMzc2NTE2OTYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "85",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjQvMC8wMzcvNjQ1LzAwMzc2NDUxOTYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjQvMC8wMzcvNjQ1LzAwMzc2NDUxOTYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "84",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOakV2TUM4d016Y3ZOak00THpBd016YzJNemcxTURndWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOakV2TUM4d016Y3ZOak00THpBd016YzJNemcxTURndWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "83",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlRWUFJFcE9aV3RzTWxSVlVrSmxhelUyVjFod1RtRnJSWGhVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlRWUFJFcE9aV3RzTWxSVlVrSmxhelUyVjFod1RtRnJSWGhVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "82",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy82MjUvMDAzNzYyNTQwNy5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy82MjUvMDAzNzYyNTQwNy5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "81",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREpOVkUxMlRVUkJlazU2V1hoTmVrRTBUa00xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREpOVkUxMlRVUkJlazU2V1hoTmVrRTBUa00xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "80",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRbEJWZW1nelZFaHdRbVZyTlRWUFJFcE9Va1pzTWxSVlVrSmxhelUyVjFoa1QyRnJhM2xVYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRbEJWZW1nelZFaHdRbVZyTlRWUFJFcE9Va1pzTWxSVlVrSmxhelUyVjFoa1QyRnJhM2xVYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "79",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjIvMC8wMzcvNTk4LzAwMzc1OTg4NzAubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjIvMC8wMzcvNTk4LzAwMzc1OTg4NzAubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "78",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFWlFWa1ZXTWxSVlVrSmxhelUyVmxSV1RsWkZNSGxVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFWlFWa1ZXTWxSVlVrSmxhelUyVmxSV1RsWkZNSGxVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "77",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREZQUkZGMlRVUkJlazU2VlRST1JFVXhUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREZQUkZGMlRVUkJlazU2VlRST1JFVXhUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "76",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NC8wLzAzNy81NzcvMDAzNzU3NzI5My5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NC8wLzAzNy81NzcvMDAzNzU3NzI5My5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "75",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjMvMC8wMzcvNTY5LzAwMzc1Njk3OTIubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjMvMC8wMzcvNTY5LzAwMzc1Njk3OTIubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "74",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUjA0MlZFaHdRbVJyTVVWVVZFNU5aV3hWZVZSWGF6UmtNREZGVkZST1QxWkdiRFZVTUZKR1RsVjRkRTFZWkU5U1JHeDJXV3BPVDAxR1FsaGhSRXBwVmtWVmVsUlZaR3BrVjFKSlZsaFdhMU5HYXprPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUjA0MlZFaHdRbVJyTVVWVVZFNU5aV3hWZVZSWGF6UmtNREZGVkZST1QxWkdiRFZVTUZKR1RsVjRkRTFZWkU5U1JHeDJXV3BPVDAxR1FsaGhSRXBwVmtWVmVsUlZaR3BrVjFKSlZsaFdhMU5HYXprPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "73",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzIvMC8wMzcvNTU1LzAwMzc1NTU3MjcubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzIvMC8wMzcvNTU1LzAwMzc1NTU3MjcubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "72",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYlU0eVZGVk5OR1F3TVRaWk0xcFBWa1pHTmxSSWNFSmtNREUyV1hwR1QxSkZNSGxVYTFKdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYlU0eVZGVk5OR1F3TVRaWk0xcFBWa1pHTmxSSWNFSmtNREUyV1hwR1QxSkZNSGxVYTFKdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "71",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYbE9VemgzVEhwQmVrNTVPREZOZWxWMlRVUkJlazU2VlhwT1ZHY3pUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYbE9VemgzVEhwQmVrNTVPREZOZWxWMlRVUkJlazU2VlhwT1ZHY3pUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "70",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9hVGgzVEhwQmVrNTVPREZOYW1kMlRVUkJlazU2VlhsUFJGRXhUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9hVGgzVEhwQmVrNTVPREZOYW1kMlRVUkJlazU2VlhsUFJGRXhUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "69",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk5lVGgzVEhwQmVrNTVPREZOYWtWMlRVUkJlazU2VlhsTlZFMHpUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk5lVGgzVEhwQmVrNTVPREZOYWtWMlRVUkJlazU2VlhsTlZFMHpUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "68",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTJ3eVZGVk5OR1F3TVRaWk0xcFBWa1ZXTmxSSWNFSmtNREUyV1hwR1RsWkZNVFpVYkZKS1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTJ3eVZGVk5OR1F3TVRaWk0xcFBWa1ZXTmxSSWNFSmtNREUyV1hwR1RsWkZNVFpVYkZKS1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "67",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzMvMC8wMzcvNTA1LzAwMzc1MDU2NzIubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzMvMC8wMzcvNTA1LzAwMzc1MDU2NzIubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "66",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFSlFWa2RrTWxSVlVrSmxhelUyVlZSV1VGSkdSVEJVYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFSlFWa2RrTWxSVlVrSmxhelUyVlZSV1VGSkdSVEJVYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "65",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODBPVEV2TURBek56UTVNVEF6Tnk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODBPVEV2TURBek56UTVNVEF6Tnk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "64",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MC50dS50di92aWQ2My8wLzAzNy80ODQvMDAzNzQ4NDAyNS5tcDQ/aG9zdD1odm0xNzBnLnR1LnR2K1o='",
"desc": "aHR0cDovL2h2bTE3MC50dS50di92aWQ2My8wLzAzNy80ODQvMDAzNzQ4NDAyNS5tcDQ/aG9zdD1odm0xNzBnLnR1LnR2K1o=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "63",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODBOemN2TURBek56UTNOekl6TkM1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODBOemN2TURBek56UTNOekl6TkM1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "62",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9RemgzVEhwQmVrNTVPREJPZWtWMlRVUkJlazU2VVROTlZHY3pUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9RemgzVEhwQmVrNTVPREJPZWtWMlRVUkJlazU2VVROTlZHY3pUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "61",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREJPYWxWMlRVUkJlazU2VVRKT1ZGbDNUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREJPYWxWMlRVUkJlazU2VVRKT1ZGbDNUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "60",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'http://el-sabrosito.com/list/dbsesp.php?id=v60'",
"desc": "http://el-sabrosito.com/list/dbsesp.php?id=v60",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "59",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'http://el-sabrosito.com/list/dbsesp.php?id=v59'",
"desc": "http://el-sabrosito.com/list/dbsesp.php?id=v59",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "58",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'http://el-sabrosito.com/list/dbsesp.php?id=v58'",
"desc": "http://el-sabrosito.com/list/dbsesp.php?id=v58",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "57",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hazEyVFVNNGQwMTZZM1pPUkZrMVRIcEJkMDE2WXpCT2Ftc3pUVVJOZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hazEyVFVNNGQwMTZZM1pPUkZrMVRIcEJkMDE2WXpCT2Ftc3pUVVJOZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "56",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk5lVGgzVEhwQmVrNTVPREJOYWtsMlRVUkJlazU2VVhsTmFrVTFUV2sxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk5lVGgzVEhwQmVrNTVPREJOYWtsMlRVUkJlazU2VVhsTmFrVTFUV2sxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "55",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDEyMC8wLzAzNy80MTUvMDAzNzQxNTc1Ny5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDEyMC8wLzAzNy80MTUvMDAzNzQxNTc1Ny5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "54",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFSk9Va1V4TWxSVlVrSmxhelUyVlZoa1RtVnNWVEZVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFSk9Va1V4TWxSVlVrSmxhelUyVlZoa1RtVnNWVEZVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "53",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRazlSZW1nelZFaHdRbVZyTlRWUFNIQlFWa2RPTWxSVlVrSmxhelUyVkZSV1QyVnRUVEZVVlUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRazlSZW1nelZFaHdRbVZyTlRWUFNIQlFWa2RPTWxSVlVrSmxhelUyVkZSV1QyVnRUVEZVVlUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "52",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRazlSZW1nelZFaHdRbVZyTlRWUFNIQlFWa1ZHTWxSVlVrSmxhelUyVkZSV1RsSkZSalpVYldzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRazlSZW1nelZFaHdRbVZyTlRWUFNIQlFWa1ZHTWxSVlVrSmxhelUyVkZSV1RsSkZSalpVYldzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "51",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVV4VFhrNGQweDZRWHBPZVRoNlQwUk5kazFFUVhwT2VrMDBUWHBqTWs5RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRXazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVV4VFhrNGQweDZRWHBPZVRoNlQwUk5kazFFUVhwT2VrMDBUWHBqTWs5RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRXazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "50",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazVsVkdnelZFaHdRbVZyTlRWUFNIQlBaV3hzTWxSVlVrSmxhelUyVkZST1QyRnNSVEZVYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazVsVkdnelZFaHdRbVZyTlRWUFNIQlBaV3hzTWxSVlVrSmxhelUyVkZST1QyRnNSVEZVYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "49",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjMvMC8wMzcvNDUwLzAwMzc0NTAwMjYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjMvMC8wMzcvNDUwLzAwMzc0NTAwMjYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "48",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzMvMC8wMzcvNDUwLzAwMzc0NTAwMTMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzMvMC8wMzcvNDUwLzAwMzc0NTAwMTMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "47",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjMvMC8wMzcvNDUwLzAwMzc0NTAwMDUubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjMvMC8wMzcvNDUwLzAwMzc0NTAwMDUubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "46",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk5lVGgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZHczFUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk5lVGgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZHczFUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "45",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZHczBUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZHczBUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "44",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hazEyVFVNNGQwMTZZM1pPUkZFMVRIcEJkMDE2WXpCT1JHczFUbnBKZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hazEyVFVNNGQwMTZZM1pPUkZFMVRIcEJkMDE2WXpCT1JHczFUbnBKZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "43",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzMC8wLzAzNy80NDkvMDAzNzQ0OTk2My5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzMC8wLzAzNy80NDkvMDAzNzQ0OTk2My5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "42",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOekl2TUM4d016Y3ZORFE1THpBd016YzBORGs1TkRjdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOekl2TUM4d016Y3ZORFE1THpBd016YzBORGs1TkRjdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "41",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy80NDkvMDAzNzQ0OTkyOS5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy80NDkvMDAzNzQ0OTkyOS5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "40",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYcE9hVGgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZGbDNUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYcE9hVGgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZGbDNUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "39",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjQvMC8wMzcvNDQ5LzAwMzc0NDk1NzMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjQvMC8wMzcvNDQ5LzAwMzc0NDk1NzMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "38",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYlU0eVZGVk5OR1F3TVRaWk0xcFBVa1pGTVZSSWNFSmtNREUyV1hwQ1QxSkhjM2hVYkZKU1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYlU0eVZGVk5OR1F3TVRaWk0xcFBVa1pGTVZSSWNFSmtNREUyV1hwQ1QxSkhjM2hVYkZKU1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "37",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZGVXdUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZGVXdUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "36",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTgvMC8wMzcvNDQ5LzAwMzc0NDk1MjQubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTgvMC8wMzcvNDQ5LzAwMzc0NDk1MjQubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "35",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalF2TUM4d016Y3ZORFE1THpBd016YzBORGsxTURRdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalF2TUM4d016Y3ZORFE1THpBd016YzBORGsxTURRdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "34",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTBNeTh3THpBek55ODBORGt2TURBek56UTBPVFEzT1M1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTBNeTh3THpBek55ODBORGt2TURBek56UTBPVFEzT1M1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "33",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYcE5RemgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZGRXlUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYcE5RemgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZGRXlUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "32",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9RemgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZGRXdUV2sxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9RemgzVEhwQmVrNTVPREJPUkd0MlRVUkJlazU2VVRCUFZGRXdUV2sxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "31",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjJReVZGVk5OR1F3TVRaWk0xcFBVa1pGTVZSSWNFSmtNREUyV1hwQ1QxSkhjM2RVVjNCR1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjJReVZGVk5OR1F3TVRaWk0xcFBVa1pGTVZSSWNFSmtNREUyV1hwQ1QxSkhjM2RVVjNCR1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "30",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODBNelV2TURBek56UXpOVEl5TWk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODBNelV2TURBek56UXpOVEl5TWk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "29",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRbEJWZW1nelZFaHdRbVZyTlRWUFJFSk9aV3hXTWxSVlVrSmxhelUyVlZod1QxWkZiRE5VYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRbEJWZW1nelZFaHdRbVZyTlRWUFJFSk9aV3hXTWxSVlVrSmxhelUyVlZod1QxWkZiRE5VYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "28",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJYcE5VemgzVEhwQmVrNTVPREJOZWxWMlRVUkJlazU2VVhwT1ZFVTBUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJYcE5VemgzVEhwQmVrNTVPREJOZWxWMlRVUkJlazU2VVhwT1ZFVTBUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "27",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFNUzh3THpBek55ODBNelV2TURBek56UXpOVEUzTnk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFNUzh3THpBek55ODBNelV2TURBek56UXpOVEUzTnk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "26",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODBNelV2TURBek56UXpOVEUyTWk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODBNelV2TURBek56UXpOVEUyTWk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "25",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyNS8wLzAzNy80MzUvMDAzNzQzNTE0My5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyNS8wLzAzNy80MzUvMDAzNzQzNTE0My5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "24",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9hVGgzVEhwQmVrNTVPREJOZWxWMlRVUkJlazU2VVhwT1ZFVjVUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9hVGgzVEhwQmVrNTVPREJOZWxWMlRVUkJlazU2VVhwT1ZFVjVUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "23",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVV4VGtNNGQweDZRWHBPZVRnd1RYcFZkazFFUVhwT2VsRjZUbFJCTTA5RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVV4VGtNNGQweDZRWHBPZVRnd1RYcFZkazFFUVhwT2VsRjZUbFJCTTA5RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "22",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWNFZHdE5OR1F3ZURaUldIQlBaVlJuZDFSWWNGWmthekZGVVZod1QyVnNSalpVYkZKQ1RUQTVSRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWNFZHdE5OR1F3ZURaUldIQlBaVlJuZDFSWWNGWmthekZGVVZod1QyVnNSalpVYkZKQ1RUQTVSRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "21",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZURjBWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWNFZHdE5OR1F3ZURaUldIQlBaVlJuZDFSWWNGWmthekZGVVZod1QyVnNSalpVYkZKQ1RXczFSRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZURjBWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWNFZHdE5OR1F3ZURaUldIQlBaVlJuZDFSWWNGWmthekZGVVZod1QyVnNSalpVYkZKQ1RXczFSRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "20",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyOC8wLzAzNy80MzQvMDAzNzQzNDI3OC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyOC8wLzAzNy80MzQvMDAzNzQzNDI3OC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "19",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk5lVGgzVEhwQmVrNTVPREJOZWxGMlRVUkJlazU2VVhwT1JFa3hUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk5lVGgzVEhwQmVrNTVPREJOZWxGMlRVUkJlazU2VVhwT1JFa3hUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "18",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYbE9hVGgzVEhwQmVrNTVPREJOZWxGMlRVUkJlazU2VVhwT1JFbDZUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYbE9hVGgzVEhwQmVrNTVPREJOZWxGMlRVUkJlazU2VVhwT1JFbDZUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "17",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0Ni8wLzAzNy80MzQvMDAzNzQzNDIyMi5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0Ni8wLzAzNy80MzQvMDAzNzQzNDIyMi5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "16",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRTlSZW1nelZFaHdRbVZyTlRWUFJFSk9aV3hHTWxSVlVrSmxhelUyVlZod1QxSkZWVEZVYldzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRTlSZW1nelZFaHdRbVZyTlRWUFJFSk9aV3hHTWxSVlVrSmxhelUyVlZod1QxSkZWVEZVYldzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "15",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXlPUzh3THpBek55ODBNelF2TURBek56UXpOREU0TkM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXlPUzh3THpBek55ODBNelF2TURBek56UXpOREU0TkM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "14",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFSk9aV3hHTWxSVlVrSmxhelUyVlZod1QxSkZWalpVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFSk9aV3hHTWxSVlVrSmxhelUyVlZod1QxSkZWalpVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "13",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0Ni8wLzAzNy80MzQvMDAzNzQzNDEwOC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0Ni8wLzAzNy80MzQvMDAzNzQzNDEwOC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "12",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9RemgzVEhwQmVrNTVPREJOUkZsMlRVUkJlazU2VVhkT2FrMTVUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9RemgzVEhwQmVrNTVPREJOUkZsMlRVUkJlazU2VVhkT2FrMTVUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "11",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODBNelF2TURBek56UXpOREEyT1M1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODBNelF2TURBek56UXpOREEyT1M1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "10",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzNi8wLzAzNy80MzMvMDAzNzQzMzY3NS5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzNi8wLzAzNy80MzMvMDAzNzQzMzY3NS5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "09",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyNC8wLzAzNy80MzMvMDAzNzQzMzY1NC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyNC8wLzAzNy80MzMvMDAzNzQzMzY1NC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "08",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDExOC8wLzAzNy80MzMvMDAzNzQzMzYzNi5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDExOC8wLzAzNy80MzMvMDAzNzQzMzYzNi5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "07",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRkJSZW1nelZFaHdRbVZyTlRWUFJFSk9aV3N4TWxSVlVrSmxhelUyVlZod1RtVnNiRFZVVjJzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRkJSZW1nelZFaHdRbVZyTlRWUFJFSk9aV3N4TWxSVlVrSmxhelUyVlZod1RtVnNiRFZVVjJzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "06",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'http://el-sabrosito.com/list/dbsesp.php?id=v6'",
"desc": "http://el-sabrosito.com/list/dbsesp.php?id=v6",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "05",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFSk9aV3N4TWxSVlVrSmxhelUyVlZod1RtVnNWVEJVV0dzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFSk9aV3N4TWxSVlVrSmxhelUyVlZod1RtVnNWVEJVV0dzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "04",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJYaFBRemgzVEhwQmVrNTVPREJOZWsxMlRVUkJlazU2VVhwTmVsVXlUMU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJYaFBRemgzVEhwQmVrNTVPREJOZWsxMlRVUkJlazU2VVhwTmVsVXlUMU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "03",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXpOaTh3THpBek55ODBNek12TURBek56UXpNelUxTmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXpOaTh3THpBek55ODBNek12TURBek56UXpNelUxTmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NC8wLzAzNy80MzMvMDAzNzQzMzU1Mi5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NC8wLzAzNy80MzMvMDAzNzQzMzU1Mi5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "01",
"titulo": "Dragon Ball Super",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZURjBWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWNFZHdE5OR1F3ZURaUldIQlBaVlJvTmxReFVsWmthekZGVVZod1QyVnJNREZVYkZKT1pEQTFjRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZURjBWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWNFZHdE5OR1F3ZURaUldIQlBaVlJvTmxReFVsWmthekZGVVZod1QyVnJNREZVYkZKT1pEQTFjRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
])