myFunction([
{
"display": "01",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZURjBWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWNFZGZHJOR1F3ZURaUldIQk9WWHBuZDFSWGNGcGthekZGVVZod1RsWkdSalZVYlhCV1RWVTVSRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZURjBWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWNFZGZHJOR1F3ZURaUldIQk9WWHBuZDFSWGNGcGthekZGVVZod1RsWkdSalZVYlhCV1RWVTVSRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "02",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVY0VDBNNGQweDZRWHBPVXpneVRucHJkazFFUVhwT1ZGa3pUMVJKTTAxRE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVY0VDBNNGQweDZRWHBPVXpneVRucHJkazFFUVhwT1ZGa3pUMVJKTTAxRE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "03",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRkJWZW1nelZFaHdRbVZyTlRWUFNHaE9Wa2RPTWxSVlVrSmxhelUyVWxob1QyVnJNREZVYkUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRkJWZW1nelZFaHdRbVZyTlRWUFNHaE9Wa2RPTWxSVlVrSmxhelUyVWxob1QyVnJNREZVYkUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "04",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXlNeTh3THpBek1TODBNall2TURBek1UUXlOamMwTUM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXlNeTh3THpBek1TODBNall2TURBek1UUXlOamMwTUM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "05",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDE0Ni8wLzAzMS80MjYvMDAzMTQyNjgxNy5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDE0Ni8wLzAzMS80MjYvMDAzMTQyNjgxNy5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "06",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZZMVZEQk5OR1F3ZURaUldIQk9WWHBuZDFSWGNGcGthekZGVVZod1RsWkdSalZVYlhCcVRrVTFSRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUlhhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZZMVZEQk5OR1F3ZURaUldIQk9WWHBuZDFSWGNGcGthekZGVVZod1RsWkdSalZVYlhCcVRrVTFSRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUlhhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "07",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRTVsVkdnelZFaHdRbVZyTlRWUFNHaE9Wa2RPTWxSVlVrSmxhelUyVWxob1QyVnNSak5VVjJzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRTVsVkdnelZFaHdRbVZyTlRWUFNHaE9Wa2RPTWxSVlVrSmxhelUyVWxob1QyVnNSak5VVjJzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "08",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDE1Mi8wLzAzMS80MjYvMDAzMTQyNjc3OC5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDE1Mi8wLzAzMS80MjYvMDAzMTQyNjc3OC5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "09",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYcE9hVGgzVEhwQmVrNVRPSHBOYWxGMlRVUkJlazVVVFhsT1JFa3dUa00xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYcE9hVGgzVEhwQmVrNVRPSHBOYWxGMlRVUkJlazVVVFhsT1JFa3dUa00xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "10",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWM1ZHeE5OR1F3ZURaUldIQlBZVlJvTTFReFVscGthekZGVVZod1QyRnJSVEZVYlhCT1RUQTVWRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZWM1ZHeE5OR1F3ZURaUldIQlBZVlJvTTFReFVscGthekZGVVZod1QyRnJSVEZVYlhCT1RUQTVWRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "11",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXlOaTh3THpBek1TODBNall2TURBek1UUXlOamc1TUM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXlOaTh3THpBek1TODBNall2TURBek1UUXlOamc1TUM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "12",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYcE9hVGgzVEhwQmVrNVRPSHBOYWxGMlRVUkJlazVVVFhsT1JFa3pUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYcE9hVGgzVEhwQmVrNVRPSHBOYWxGMlRVUkJlazVVVFhsT1JFa3pUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "13",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyNi8wLzAzNy8yMzMvMDAzNzIzMzQyMi5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyNi8wLzAzNy8yMzMvMDAzNzIzMzQyMi5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "14",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTBOeTh3THpBek5pODNNall2TURBek5qY3lOakl3T0M1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTBOeTh3THpBek5pODNNall2TURBek5qY3lOakl3T0M1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "15",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyNi8wLzAzNy8xMTcvMDAzNzExNzQyMy5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyNi8wLzAzNy8xMTcvMDAzNzExNzQyMy5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "16",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVY2VFZNNGQweDZRWHBPZVRoNFRWUmpkazFFUVhwT2VrVjRUbnBSZWs5RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVY2VFZNNGQweDZRWHBPZVRoNFRWUmpkazFFUVhwT2VrVjRUbnBSZWs5RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "17",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDE1My8wLzAzNy8xMTcvMDAzNzExNzQ0MC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDE1My8wLzAzNy8xMTcvMDAzNzExNzQ0MC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "18",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTW0wNU0yTXlMblIxTG5SMkwzWnBaREUwTnk4d0x6QXpOeTh4TVRjdk1EQXpOekV4TnpRME15NXRjRFEvYUc5emREMW9kakU0TXk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyTW0wNU0yTXlMblIxTG5SMkwzWnBaREUwTnk4d0x6QXpOeTh4TVRjdk1EQXpOekV4TnpRME15NXRjRFEvYUc5emREMW9kakU0TXk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "19",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSllhRkJSZW1nelZFaHdRbVZyTVZSUFJFSk9ZVzFPTWxSVlVrSmxhekZWVlZoc1QyVnJiRFJVYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSllhRkJSZW1nelZFaHdRbVZyTVZSUFJFSk9ZVzFPTWxSVlVrSmxhekZWVlZoc1QyVnJiRFJVYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "20",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTlsVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hXTWxSVlVrSmxhelZWVkZoc1QxWkZWalpVTUUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTlsVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hXTWxSVlVrSmxhelZWVkZoc1QxWkZWalpVTUUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "21",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRkJWZW1nelZFaHdRbVZyTlRWUFNHaE9Wa2RPTWxSVlVrSmxhelUyVWxob1QyVnNSWGRVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRkJWZW1nelZFaHdRbVZyTlRWUFNHaE9Wa2RPTWxSVlVrSmxhelUyVWxob1QyVnNSWGRVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "22",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRTVsVkdnelZFaHdRbVZyTlRWUFNHeE9aV3N4TWxSVlVrSmxhelUyVTFod1RtVnNSVEJVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRTVsVkdnelZFaHdRbVZyTlRWUFNHeE9aV3N4TWxSVlVrSmxhelUyVTFod1RtVnNSVEJVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "23",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDEzNy8wLzAzNS8zMjUvMDAzNTMyNTE3OS5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDEzNy8wLzAzNS8zMjUvMDAzNTMyNTE3OS5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "24",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRkJSZW1nelZFaHdRbVZyTlRWUFNHeE9aV3N4TWxSVlVrSmxhelUyVTFod1RtVnNSVEJVV0dzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRkJSZW1nelZFaHdRbVZyTlRWUFNHeE9aV3N4TWxSVlVrSmxhelUyVTFod1RtVnNSVEJVV0dzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "25",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFNeTh3THpBek55OHlNek12TURBek56SXpNelE0Tnk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFNeTh3THpBek55OHlNek12TURBek56SXpNelE0Tnk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "26",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTBPUzh3THpBek55OHhNVGN2TURBek56RXhOelExT1M1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTBPUzh3THpBek55OHhNVGN2TURBek56RXhOelExT1M1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "27",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFNeTh3THpBek1TODBNamN2TURBek1UUXlOelF5T1M1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFNeTh3THpBek1TODBNamN2TURBek1UUXlOelF5T1M1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "28",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hXTWxSVlVrSmxhelZWVkZoc1QxWkZhM2RVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hXTWxSVlVrSmxhelZWVkZoc1QxWkZhM2RVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "29",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1Mi8wLzAzNy8yMzMvMDAzNzIzMzUwMC5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1Mi8wLzAzNy8yMzMvMDAzNzIzMzUwMC5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "30",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXpOaTh3THpBek5TOHpNalV2TURBek5UTXlOVEkzTmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXpOaTh3THpBek5TOHpNalV2TURBek5UTXlOVEkzTmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "31",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzNi8wLzAzNS8zMjUvMDAzNTMyNTI4My5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzNi8wLzAzNS8zMjUvMDAzNTMyNTI4My5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "32",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTF0VFhsTWJsSXhURzVTTWt3elduQmFSRVV3VG5rNGQweDZRWHBOVXpnd1RXcGpkazFFUVhwTlZGRjVUbnBSZWsxNU5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTF0VFhsTWJsSXhURzVTTWt3elduQmFSRVV3VG5rNGQweDZRWHBOVXpnd1RXcGpkazFFUVhwTlZGRjVUbnBSZWsxNU5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "33",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDEyNi8wLzAzNi8wODkvMDAzNjA4OTI4MS5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDEyNi8wLzAzNi8wODkvMDAzNjA4OTI4MS5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "34",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERXpNaTh3THpBek55OHlNek12TURBek56SXpNelUzT0M1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERXpNaTh3THpBek55OHlNek12TURBek56SXpNelUzT0M1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "35",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYbE9lVGgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2FrRXpUa00xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYbE9lVGgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2FrRXpUa00xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "36",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDExOS8wLzAzNy8xMTcvMDAzNzExNzQ3Ni5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDExOS8wLzAzNy8xMTcvMDAzNzExNzQ3Ni5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "37",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hzTWxSVlVrSmxhelZWVkZoc1QyRnJSVEZVVlUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hzTWxSVlVrSmxhelZWVkZoc1QyRnJSVEZVVlUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "38",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVV3VGtNNGQweDZRWHBPYVRoM1QwUm5kazFFUVhwT2FrRTBUMFJqZUU1VE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRXazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVV3VGtNNGQweDZRWHBPYVRoM1QwUm5kazFFUVhwT2FrRTBUMFJqZUU1VE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRXazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "39",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJYcE9lVGgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2FrVjVUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJYcE9lVGgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2FrVjVUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "40",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9RemgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2FrVjZUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9RemgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2FrVjZUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "41",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDEzNy8wLzAzNS8zMjYvMDAzNTMyNjE2OS5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDEzNy8wLzAzNS8zMjYvMDAzNTMyNjE2OS5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "42",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzNi8wLzAzNS8zMjYvMDAzNTMyNjE4MC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzNi8wLzAzNS8zMjYvMDAzNTMyNjE4MC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "43",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJYcE9lVGgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2FrVTFUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJYcE9lVGgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2FrVTFUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "44",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVFl2TUM4d016VXZNekkyTHpBd016VXpNall5TVRJdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVFl2TUM4d016VXZNekkyTHpBd016VXpNall5TVRJdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "45",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYbE9hVGgzVEhwQmVrNTVPSGhOVkdOMlRVUkJlazU2UlhoT2VsRTBUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYbE9hVGgzVEhwQmVrNTVPSGhOVkdOMlRVUkJlazU2UlhoT2VsRTBUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "46",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hzTWxSVlVrSmxhelZWVkZoc1QyRnJiRFpVYldzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hzTWxSVlVrSmxhelZWVkZoc1QyRnJiRFpVYldzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "47",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hzTWxSVlVrSmxhelZWVkZoc1QyRnJhM2hVVlUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hzTWxSVlVrSmxhelZWVkZoc1QyRnJhM2hVVlUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "48",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTlsVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hzTWxSVlVrSmxhelZWVkZoc1QyRnJhM2xVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTlsVkdnelZFaHdRbVZyTlZSUFNIQk9ZV3hzTWxSVlVrSmxhelZWVkZoc1QyRnJhM2xVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "49",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek5TOHpNall2TURBek5UTXlOakkzTkM1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek5TOHpNall2TURBek5UTXlOakkzTkM1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "50",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJYcE9lVGgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2Fra3pUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJYcE9lVGgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2Fra3pUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "51",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRTVSZW1nelZFaHdRbVZyTVZSUFJFSk9ZVzFPTWxSVlVrSmxhekZWVlZoc1QyVnNiRFZVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRTVSZW1nelZFaHdRbVZyTVZSUFJFSk9ZVzFPTWxSVlVrSmxhekZWVlZoc1QyVnNiRFZVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "52",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXpOaTh3THpBek5TOHpNall2TURBek5UTXlOak14T0M1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXpOaTh3THpBek5TOHpNall2TURBek5UTXlOak14T0M1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "53",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYcE9hVGgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2FtZDZUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYcE9hVGgzVEhwQmVrNVRPSHBOYWxsMlRVUkJlazVVVFhsT2FtZDZUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "54",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYbFBVemgzVEhwQmVrMVRPREJOYW1kMlRVUkJlazFVVVhsUFJHTjNUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJYbFBVemgzVEhwQmVrMVRPREJOYW1kMlRVUkJlazFVVVhsUFJHTjNUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "55",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NC8wLzAzNS8zMjYvMDAzNTMyNjg3Ni5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NC8wLzAzNS8zMjYvMDAzNTMyNjg3Ni5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "56",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXpOaTh3THpBek5TOHpNall2TURBek5UTXlOamt6TXk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXpOaTh3THpBek5TOHpNall2TURBek5UTXlOamt6TXk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "57",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'http://proxy-041.dc3.dailymotion.com/sec(2985928e14a4aea6d78142a987ccbe38)/video/641/091/281190146_mp4_h264_aac_hq_1.m3u8'",
"desc": "http://proxy-041.dc3.dailymotion.com/sec(2985928e14a4aea6d78142a987ccbe38)/video/641/091/281190146_mp4_h264_aac_hq_1.m3u8",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "58",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERXpOeTh3THpBek5TOHpNamN2TURBek5UTXlOekF3T0M1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERXpOeTh3THpBek5TOHpNamN2TURBek5UTXlOekF3T0M1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "59",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlZSUFNIQk9ZVzFPTWxSVlVrSmxhelZWVkZoc1QyVnJSalZVYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTloVkdnelZFaHdRbVZyTlZSUFNIQk9ZVzFPTWxSVlVrSmxhelZWVkZoc1QyVnJSalZVYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "60",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZZMlZHMXJOR1F3ZURaUldIQlBWWHBvTmxSWGNHcGthekZGVVZod1QxWkZNVFZVYm5CQ1pXczFOVTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUlhhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZZMlZHMXJOR1F3ZURaUldIQlBWWHBvTmxSWGNHcGthekZGVVZod1QxWkZNVFZVYm5CQ1pXczFOVTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUlhhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "61",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXpOaTh3THpBek5TOHpNamN2TURBek5UTXlOekEwTmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXpOaTh3THpBek5TOHpNamN2TURBek5UTXlOekEwTmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "62",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTlsVkdnelZFaHdRbVZyTlZSUFNIQk9ZVzFPTWxSVlVrSmxhelZWVkZoc1QyVnJSWGhVVlUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlljRTlsVkdnelZFaHdRbVZyTlZSUFNIQk9ZVzFPTWxSVlVrSmxhelZWVkZoc1QyVnJSWGhVVlUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "63",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERXpOeTh3THpBek5TOHpNamN2TURBek5UTXlOekEyTUM1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERXpOeTh3THpBek5TOHpNamN2TURBek5UTXlOekEyTUM1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "64",
"titulo": "Shaman King",
"subt": "Audio Lat.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzNi8wLzAzNS8zMjcvMDAzNTMyNzA3NC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzNi8wLzAzNS8zMjcvMDAzNTMyNzA3NC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},

])