myFunction([
{
"display": "01",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaRGN6THpBdk1ETTNMelUzTnk4d01ETTNOVGMzTXpBMUxtMXdORDlvYjNOMFBXaDJiVEUzTUdjdWRIVXVkSFk9K0c='",
"desc": "YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaRGN6THpBdk1ETTNMelUzTnk4d01ETTNOVGMzTXpBMUxtMXdORDlvYjNOMFBXaDJiVEUzTUdjdWRIVXVkSFk9K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaREV5TXk4d0x6QXpOeTgxTnpjdk1EQXpOelUzTnpNeE5pNXRjRFEvYUc5emREMW9kakU0TWk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaREV5TXk4d0x6QXpOeTgxTnpjdk1EQXpOelUzTnpNeE5pNXRjRFEvYUc5emREMW9kakU0TWk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "03",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTBOQzh3THpBek55ODFOemN2TURBek56VTNOelEzTlM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTBOQzh3THpBek55ODFOemN2TURBek56VTNOelEzTlM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "04",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRmwzVEhwQmRrMUVUVE5NZWxVelRuazRkMDFFVFROT1ZHTXpUa1JqTWt4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRmwzVEhwQmRrMUVUVE5NZWxVelRuazRkMDFFVFROT1ZHTXpUa1JqTWt4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "05",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjEvMC8wMzcvNTc3LzAwMzc1NzczMzgubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjEvMC8wMzcvNTc3LzAwMzc1NzczMzgubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "06",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTBZeVZGVk5OR1F3TVRaWk0xcFBWa2ROZWxSSWNFSmtNREUyV1hwR1QyVnRUWGhVV0hCT1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTBZeVZGVk5OR1F3TVRaWk0xcFBWa2ROZWxSSWNFSmtNREUyV1hwR1QyVnRUWGhVV0hCT1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "07",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTF0VFhsTWJsSXhURzVTTWt3elduQmFSRlUxVEhwQmRrMUVUVE5NZWxVelRuazRkMDFFVFROT1ZHTXpUWHBOTlV4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTF0VFhsTWJsSXhURzVTTWt3elduQmFSRlUxVEhwQmRrMUVUVE5NZWxVelRuazRkMDFFVFROT1ZHTXpUWHBOTlV4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "08",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy81NzcvMDAzNzU3NzUyOC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy81NzcvMDAzNzU3NzUyOC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "09",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFWlFVa1pHTWxSVlVrSmxhelUyVmxSU1QxSkZSWGRVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFWlFVa1pHTWxSVlVrSmxhelUyVmxSU1QxSkZSWGRVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "10",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkZZeVZGVk5OR1F3TVRaWk0xcFBWa2ROZWxSSWNFSmtNREUyV1hwR1QyVnRUWGhVYTFKQ1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkZZeVZGVk5OR1F3TVRaWk0xcFBWa2ROZWxSSWNFSmtNREUyV1hwR1QyVnRUWGhVYTFKQ1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "11",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOamN2TUM4d016Y3ZOVGMzTHpBd016YzFOemMxTkRrdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOamN2TUM4d016Y3ZOVGMzTHpBd016YzFOemMxTkRrdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "12",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODFOemN2TURBek56VTNOelkxTmk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODFOemN2TURBek56VTNOelkxTmk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "13",
"titulo": "High School DxD New",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODFOemN2TURBek56VTNOelUwTmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODFOemN2TURBek56VTNOelUwTmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
])