myFunction([
{
"display": "01",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzMvMC8wMzcvNTc1LzAwMzc1NzU5MzgubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzMvMC8wMzcvNTc1LzAwMzc1NzU5MzgubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "02",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NC8wLzAzNy81NzUvMDAzNzU3NTg4Ny5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NC8wLzAzNy81NzUvMDAzNzU3NTg4Ny5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "03",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk5lVGgzVEhwQmVrNTVPREZPZWxWMlRVUkJlazU2VlROT1ZHc3dUV2sxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk5lVGgzVEhwQmVrNTVPREZPZWxWMlRVUkJlazU2VlROT1ZHc3dUV2sxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "04",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbU4yVFVNNGQwMTZZM1pPVkdNeFRIcEJkMDE2WXpGT2VsVTFUMVJCZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbU4yVFVNNGQwMTZZM1pPVkdNeFRIcEJkMDE2WXpGT2VsVTFUMVJCZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "05",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjcvMC8wMzcvNTc2LzAwMzc1NzYwMDYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjcvMC8wMzcvNTc2LzAwMzc1NzYwMDYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "06",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjJReVZGVk5OR1F3TVRaWk0xcFBWa2ROZVZSSWNFSmtNREUyV1hwR1QyVnNiRE5VYkZKdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjJReVZGVk5OR1F3TVRaWk0xcFBWa2ROZVZSSWNFSmtNREUyV1hwR1QyVnNiRE5VYkZKdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "07",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjJReVZGVk5OR1F3TVRaWk0xcFBWa2ROZVZSSWNFSmtNREUyV1hwR1QyVnNiRE5VYkZKdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjJReVZGVk5OR1F3TVRaWk0xcFBWa2ROZVZSSWNFSmtNREUyV1hwR1QyVnNiRE5VYkZKdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "08",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOamd2TUM4d016Y3ZOVGMyTHpBd016YzFOell4TnpjdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOamd2TUM4d016Y3ZOVGMyTHpBd016YzFOell4TnpjdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "09",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFWlBaV3hzTWxSVlVrSmxhelUyVmxST1QyRnJWVEJVYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFWlBaV3hzTWxSVlVrSmxhelUyVmxST1QyRnJWVEJVYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "10",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTBZeVZGVk5OR1F3TVRaWk0xcFBWa2ROZVZSSWNFSmtNREUyV1hwR1QyVnNiRFZVV0hCU1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTBZeVZGVk5OR1F3TVRaWk0xcFBWa2ROZVZSSWNFSmtNREUyV1hwR1QyVnNiRFZVV0hCU1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "11",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFWlBaV3hzTWxSVlVrSmxhelUyVmxST1QyRnJhM2RVYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFWlBaV3hzTWxSVlVrSmxhelUyVmxST1QyRnJhM2RVYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "12",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTYvMC8wMzcvNTc2LzAwMzc1NzYyNzIubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTYvMC8wMzcvNTc2LzAwMzc1NzYyNzIubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "13",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJUQk9VemgzVEhwQmVrNTVPREZPZWxsMlRVUkJlazU2VlROT2FtZDRUV2sxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJUQk9VemgzVEhwQmVrNTVPREZPZWxsMlRVUkJlazU2VlROT2FtZDRUV2sxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "Pelicula",
"titulo": "Chuunibyou demo koi ga shitai",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1My8wLzAzNy81NzYvMDAzNzU3Njc3NC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1My8wLzAzNy81NzYvMDAzNzU3Njc3NC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},




])