myFunction([
{
"display": "01",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOak12TUM4d016Y3ZOVGM0THpBd016YzFOemd3TWpndWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOak12TUM4d016Y3ZOVGM0THpBd016YzFOemd3TWpndWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkVZeVZGVk5OR1F3TVRaWk0xcFBWa2ROTUZSSWNFSmtNREUyV1hwR1QyVnRaRE5VV0hCQ1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkVZeVZGVk5OR1F3TVRaWk0xcFBWa2ROTUZSSWNFSmtNREUyV1hwR1QyVnRaRE5VV0hCQ1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "03",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODFOemd2TURBek56VTNPREF6TXk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODFOemd2TURBek56VTNPREF6TXk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "04",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUm13eVZGVk5OR1F3TVRaWk0xcFBWa2ROTUZSSWNFSmtNREUyV1hwR1QyVnRaRE5VV0hCR1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUm13eVZGVk5OR1F3TVRaWk0xcFBWa2ROTUZSSWNFSmtNREUyV1hwR1QyVnRaRE5VV0hCR1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "05",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYXpFeVZGVk5OR1F3TVRaWk0xcFBWa2RrTkZSSWNFSmtNREUyV1hwR1VGSkZWWHBVYTFKeVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYXpFeVZGVk5OR1F3TVRaWk0xcFBWa2RrTkZSSWNFSmtNREUyV1hwR1VGSkZWWHBVYTFKeVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "06",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOakV2TUM4d016Y3ZOVGc0THpBd016YzFPRGc0TlRZdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOakV2TUM4d016Y3ZOVGc0THpBd016YzFPRGc0TlRZdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "07",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbGwyVFVNNGQwMTZZM1pPVkdzeVRIcEJkMDE2WXpGUFZGa3dUbFJaZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbGwyVFVNNGQwMTZZM1pPVkdzeVRIcEJkMDE2WXpGUFZGa3dUbFJaZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "08",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVGN2TUM4d016Y3ZOakF6THpBd016YzJNRE00TmpndWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVGN2TUM4d016Y3ZOakF6THpBd016YzJNRE00TmpndWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "09",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaREUxTlM4d0x6QXpOeTgyTVRBdk1EQXpOell4TURrNE1pNXRjRFEvYUc5emREMW9kakU0TXk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaREUxTlM4d0x6QXpOeTgyTVRBdk1EQXpOell4TURrNE1pNXRjRFEvYUc5emREMW9kakU0TXk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "10",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODJNVFl2TURBek56WXhOamswTnk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODJNVFl2TURBek56WXhOamswTnk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "11",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYXpFeVZGVk5OR1F3TVRaWk0xcFBZV3RzTmxSSWNFSmtNREUyV1hwS1RtRnJNVFZVTUZKU1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYXpFeVZGVk5OR1F3TVRaWk0xcFBZV3RzTmxSSWNFSmtNREUyV1hwS1RtRnJNVFZVTUZKU1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "12",
"titulo": "Masamune Kun No Revenge",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTFZeVZGVk5OR1F3TVRaWk0xcFBZV3N4TTFSSWNFSmtNREUyV1hwS1RtVnJSak5VVlZKdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTFZeVZGVk5OR1F3TVRaWk0xcFBZV3N4TTFSSWNFSmtNREUyV1hwS1RtVnJSak5VVlZKdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

])