myFunction([
{
"display": "01",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalF2TUM4d016Y3ZOalE0THpBd016YzJORGc1T0RNdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalF2TUM4d016Y3ZOalE0THpBd016YzJORGc1T0RNdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFcFBVa2QwTWxSVlVrSmxhelUyVjFSQ1VGWkZWak5VYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFcFBVa2QwTWxSVlVrSmxhelUyVjFSQ1VGWkZWak5VYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "03",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOak12TUM4d016Y3ZOalE1THpBd016YzJORGt4TURrdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOak12TUM4d016Y3ZOalE1THpBd016YzJORGt4TURrdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "04",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREpPUkdkMlRVUkJlazU2V1RCUFJHczBUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREpPUkdkMlRVUkJlazU2V1RCUFJHczBUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "05",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXlOQzh3THpBek55ODJORGt2TURBek56WTBPVEV5Tnk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXlOQzh3THpBek55ODJORGt2TURBek56WTBPVEV5Tnk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "06",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjYvMC8wMzcvNjQ5LzAwMzc2NDkyMzIubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjYvMC8wMzcvNjQ5LzAwMzc2NDkyMzIubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "07",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzIvMC8wMzcvNjQ5LzAwMzc2NDkyMzcubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzIvMC8wMzcvNjQ5LzAwMzc2NDkyMzcubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "08",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTcvMC8wMzcvNjQ5LzAwMzc2NDkxMjkubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTcvMC8wMzcvNjQ5LzAwMzc2NDkxMjkubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "09",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjA0eVZGVk5OR1F3TVRaWk0xcFBZV3hGTUZSSWNFSmtNREUyV1hwS1QxSkhZekZVVlZKcVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjA0eVZGVk5OR1F3TVRaWk0xcFBZV3hGTUZSSWNFSmtNREUyV1hwS1QxSkhZekZVVlZKcVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "10",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREpPUkdkMlRVUkJlazU2V1RCUFJHY3lUa00xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREpPUkdkMlRVUkJlazU2V1RCUFJHY3lUa00xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "11",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODJORGd2TURBek56WTBPRGczTXk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODJORGd2TURBek56WTBPRGczTXk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "12",
"titulo": "Ladies vs Butlers",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlsYXpFeVZGVk5OR1F3TVRaWk0xcFBZV3hGTUZSSWNFSmtNREUyV1hwS1QxSkhZekJVYm5CV1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlsYXpFeVZGVk5OR1F3TVRaWk0xcFBZV3hGTUZSSWNFSmtNREUyV1hwS1QxSkhZekJVYm5CV1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
])