myFunction([
{
"display": "01",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9la2wyVFVNNGQwMTZZM1pPVkVFelRIcEJkMDE2WXpGTlJHTXlUbnBaZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9la2wyVFVNNGQwMTZZM1pPVkVFelRIcEJkMDE2WXpGTlJHTXlUbnBaZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "02",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTYvMC8wMzcvNTA3LzAwMzc1MDc2ODcubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTYvMC8wMzcvNTA3LzAwMzc1MDc2ODcubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "03",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREZOUkdOMlRVUkJlazU2VlhkT2Vsa3lUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREZOUkdOMlRVUkJlazU2VlhkT2Vsa3lUVU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "04",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NS8wLzAzNy81MDcvMDAzNzUwNzY2MS5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NS8wLzAzNy81MDcvMDAzNzUwNzY2MS5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "05",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTFZeVZGVk5OR1F3TVRaWk0xcFBWa1ZGZWxSSWNFSmtNREUyV1hwR1RsSkhUWGxVYlhCV1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTFZeVZGVk5OR1F3TVRaWk0xcFBWa1ZGZWxSSWNFSmtNREUyV1hwR1RsSkhUWGxVYlhCV1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "06",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjIvMC8wMzcvNTA3LzAwMzc1MDc3MTUubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjIvMC8wMzcvNTA3LzAwMzc1MDc3MTUubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "07",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVGt2TUM4d016Y3ZOVEEzTHpBd016YzFNRGM0TWpRdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVGt2TUM4d016Y3ZOVEEzTHpBd016YzFNRGM0TWpRdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "08",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTBZeVZGVk5OR1F3TVRaWk0xcFBWa1ZGZWxSSWNFSmtNREUyV1hwR1RsSkhUWGxVTUZKeVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTBZeVZGVk5OR1F3TVRaWk0xcFBWa1ZGZWxSSWNFSmtNREUyV1hwR1RsSkhUWGxVTUZKeVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "09",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOamd2TUM4d016Y3ZOVEEzTHpBd016YzFNRGMyTmpJdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOamd2TUM4d016Y3ZOVEEzTHpBd016YzFNRGMyTmpJdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "10",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOamd2TUM4d016Y3ZOVEEzTHpBd016YzFNRGMyTnprdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOamd2TUM4d016Y3ZOVEEzTHpBd016YzFNRGMyTnprdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "11",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTBZeVZGVk5OR1F3TVRaWk0xcFBWa1ZGZWxSSWNFSmtNREUyV1hwR1RsSkhUWHBVVlZKR1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTBZeVZGVk5OR1F3TVRaWk0xcFBWa1ZGZWxSSWNFSmtNREUyV1hwR1RsSkhUWHBVVlZKR1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "12",
"titulo": "Juuou Mujin no Fafnir",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOekl2TUM4d016Y3ZOVEEzTHpBd016YzFNRGMyTnpNdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOekl2TUM4d016Y3ZOVEEzTHpBd016YzFNRGMyTnpNdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
},
])