myFunction([
{
"display": "01",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0OS8wLzAzNy81ODUvMDAzNzU4NTE4Ni5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0OS8wLzAzNy81ODUvMDAzNzU4NTE4Ni5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjAvMC8wMzcvNTg1LzAwMzc1ODUxODcubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjAvMC8wMzcvNTg1LzAwMzc1ODUxODcubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "03",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFWlFVa1pXTWxSVlVrSmxhelUyVmxSU1QxWkZiRE5VYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlWZW1nelZFaHdRbVZyTlRWUFJFWlFVa1pXTWxSVlVrSmxhelUyVmxSU1QxWkZiRE5VYTAweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "04",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREZQUkZWMlRVUkJlazU2VlRST1ZGbDZUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREZQUkZWMlRVUkJlazU2VlRST1ZGbDZUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "05",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUm13eVZGVk5OR1F3TVRaWk0xcFBWa2RqZUZSSWNFSmtNREUyV1hwR1VGSkdWWGhVYm5CeVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUm13eVZGVk5OR1F3TVRaWk0xcFBWa2RqZUZSSWNFSmtNREUyV1hwR1VGSkdWWGhVYm5CeVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "06",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0NC8wLzAzNy81ODUvMDAzNzU4NTcxMS5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0NC8wLzAzNy81ODUvMDAzNzU4NTcxMS5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "07",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NS8wLzAzNy81ODUvMDAzNzU4NTU4MS5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NS8wLzAzNy81ODUvMDAzNzU4NTU4MS5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "08",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE0NS8wLzAzNy81ODUvMDAzNzU4NTYyOC5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE0NS8wLzAzNy81ODUvMDAzNzU4NTYyOC5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "09",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbEYyVFVNNGQwMTZZM1pPVkdjeFRIcEJkMDE2WXpGUFJGVXlUa1JKZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbEYyVFVNNGQwMTZZM1pPVkdjeFRIcEJkMDE2WXpGUFJGVXlUa1JKZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "10",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjJReVZGVk5OR1F3TVRaWk0xcFBWa2RqZUZSSWNFSmtNREUyV1hwR1VGSkdWVEJVV0hCT1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjJReVZGVk5OR1F3TVRaWk0xcFBWa2RqZUZSSWNFSmtNREUyV1hwR1VGSkdWVEJVV0hCT1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "11",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODFPRFV2TURBek56VTROVFl6Tmk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODFPRFV2TURBek56VTROVFl6Tmk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "12",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREZQUkZWMlRVUkJlazU2VlRST1ZHZDRUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREZQUkZWMlRVUkJlazU2VlRST1ZHZDRUME0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "13",
"titulo": "Magikano",
"subt": "Audio Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODFPRFV2TURBek56VTROVFk0TUM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODFPRFV2TURBek56VTROVFk0TUM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
])