myFunction([
{
"display": "Pelicula",
"titulo": "La batalla de los dioses",
"subt": "Audio Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjgvMC8wMzcvNTkzLzAwMzc1OTM2NjMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjgvMC8wMzcvNTkzLzAwMzc1OTM2NjMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "img/dbs.png",
"postervid": "'img/postervid.png'",
},
{
"display": "Pelicula",
"titulo": "La Resurreccion de Freezer",
"subt": "Audio Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha2wyVFVNNGQwMTZZM1pPVkd0NlRIcEJkMDE2WXpGUFZFMHlUbFJOZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha2wyVFVNNGQwMTZZM1pPVkd0NlRIcEJkMDE2WXpGUFZFMHlUbFJOZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "img/rfreezer.jpg",
"postervid": "'img/postervid.png'",
},
{
"display": "Pelicula",
"titulo": "El Poder Invencible",
"subt": "Audio Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9la2wyVFVNNGQwMTZZM1pPVkd0NlRIcEJkMDE2WXpGUFZFMDFUMFJqZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9la2wyVFVNNGQwMTZZM1pPVkd0NlRIcEJkMDE2WXpGUFZFMDFUMFJqZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "img/pinvencible.png",
"postervid": "'img/postervid.png'",
},
{
"display": "Pelicula",
"titulo": "El Hermano de Vegeta",
"subt": "Audio Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkd3eVZGVk5OR1F3TVRaWk0xcFBWa2R6ZVZSSWNFSmtNREUyV1hwR1VGWkdiRE5VYkZKQ1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkd3eVZGVk5OR1F3TVRaWk0xcFBWa2R6ZVZSSWNFSmtNREUyV1hwR1VGWkdiRE5VYkZKQ1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "img/hermanovegeta.jpg",
"postervid": "'img/postervid.png'",
},
{
"display": "Pelicula",
"titulo": "El episodio de Bardock",
"subt": "Audio Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NS8wLzAzNy81OTYvMDAzNzU5NjA2Ni5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NS8wLzAzNy81OTYvMDAzNzU5NjA2Ni5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "img/bardock.jpg",
"postervid": "'img/postervid.png'",
},

])