myFunction([
{
"display": "01",
"titulo": "The Flash",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjcvMC8wMzgvMTAzLzAwMzgxMDM2MzUubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOekl2TUM4d016Z3ZNVEF6THpBd016Z3hNRE0yTkRZdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "The Flash",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzIvMC8wMzgvMTAyLzAwMzgxMDI4MDYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzIvMC8wMzgvMTAyLzAwMzgxMDI4MDYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "03",
"titulo": "The Flash",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOak12TUM4d016Z3ZNVEF5THpBd016Z3hNREk0TURVdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOak12TUM4d016Z3ZNVEF5THpBd016Z3hNREk0TURVdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "04",
"titulo": "The Flash",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzIvMC8wMzgvMTAyLzAwMzgxMDI4MDYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNzIvMC8wMzgvMTAyLzAwMzgxMDI4MDYubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "05",
"titulo": "The Flash",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalF2TUM4d016Z3ZNVEF5THpBd016Z3hNREk0TURjdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalF2TUM4d016Z3ZNVEF5THpBd016Z3hNREk0TURjdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

])