myFunction([
{
"display": "47",
"titulo": "Pokemon XYZ",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9WR2QyVFVNNGQwMTZZM1pPUkdjMFRIcEJkMDE2WXpCUFJHZDVUbFJWZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9WR2QyVFVNNGQwMTZZM1pPUkdjMFRIcEJkMDE2WXpCUFJHZDVUbFJWZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "48",
"titulo": "Pokemon XYZ Especial 1",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREJQVkVGMlRVUkJlazU2VVRWTlJFVjNUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREJQVkVGMlRVUkJlazU2VVRWTlJFVjNUbmsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "49",
"titulo": "Pokemon XYZ Especial 2",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZURjBWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUmxWNlZFaHdRbVJyTVVWVVZFNU5aV3hGTVZSdGF6UmtNREZGVkZST1QxSkhjM2xVTUZKV1RWVjRkRTFZWkU5U1JHeDJXV3BPVDAxR1FsaGhSRXBwVmtWVmVsUlZaR3BrVjFKSlZsaFdhMU5HYXprPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZURjBWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUmxWNlZFaHdRbVJyTVVWVVZFNU5aV3hGTVZSdGF6UmtNREZGVkZST1QxSkhjM2xVTUZKV1RWVjRkRTFZWkU5U1JHeDJXV3BPVDAxR1FsaGhSRXBwVmtWVmVsUlZaR3BrVjFKSlZsaFdhMU5HYXprPStW",
"onc": "'myVid'",
"imag": "poster.png",
},



])