myFunction([
{
"display": "01",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDE0Ni8wLzAzNy82MTEvMDAzNzYxMTQ1MS5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDE0Ni8wLzAzNy82MTEvMDAzNzYxMTQ1MS5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDE1Ni8wLzAzNy82MTEvMDAzNzYxMTQyOC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDE1Ni8wLzAzNy82MTEvMDAzNzYxMTQyOC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "03",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSR041VEhwQmRrMUVUVE5NZWxsNFRWTTRkMDFFVFROT2FrVjRUa1JOZDB4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSR041VEhwQmRrMUVUVE5NZWxsNFRWTTRkMDFFVFROT2FrVjRUa1JOZDB4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "04",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRmswVEhwQmRrMUVUVE5NZWxsNFRWTTRkMDFFVFROT2FrVjRUbXBCZUV4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRmswVEhwQmRrMUVUVE5NZWxsNFRWTTRkMDFFVFROT2FrVjRUbXBCZUV4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "05",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDY1LzAvMDM3LzYxMS8wMDM3NjExNDU2Lm1wND9ob3N0PWh2bTE3MGcudHUudHYrWg=='",
"desc": "aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDY1LzAvMDM3LzYxMS8wMDM3NjExNDU2Lm1wND9ob3N0PWh2bTE3MGcudHUudHYrWg==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "06",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDY1LzAvMDM3LzYxMS8wMDM3NjExNjAwLm1wND9ob3N0PWh2bTE3MGcudHUudHYrWg=='",
"desc": "aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDY1LzAvMDM3LzYxMS8wMDM3NjExNjAwLm1wND9ob3N0PWh2bTE3MGcudHUudHYrWg==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "07",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaRFkyTHpBdk1ETTNMell4TVM4d01ETTNOakV4TkRJeExtMXdORDlvYjNOMFBXaDJiVEUzTUdjdWRIVXVkSFk9K0c='",
"desc": "YUhSMGNEb3ZMMmgyTW0wNU1tTXlMblIxTG5SMkwzWnBaRFkyTHpBdk1ETTNMell4TVM4d01ETTNOakV4TkRJeExtMXdORDlvYjNOMFBXaDJiVEUzTUdjdWRIVXVkSFk9K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "08",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDE1Ni8wLzAzNy82MTEvMDAzNzYxMTQyOC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDE1Ni8wLzAzNy82MTEvMDAzNzYxMTQyOC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "09",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjYvMC8wMzcvNjE1LzAwMzc2MTU3NjkubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjYvMC8wMzcvNjE1LzAwMzc2MTU3NjkubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "10",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFcE9Wa2RrTWxSVlVrSmxhelUyVjFob1VGSkdhekJVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bGEzaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazlSZW1nelZFaHdRbVZyTlRWUFJFcE9Wa2RrTWxSVlVrSmxhelUyVjFob1VGSkdhekJVTVUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWlZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "11",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbGwyVFVNNGQwMTZZM1pPYWtrd1RIcEJkMDE2WXpKTmFsRXdUVlJqZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbGwyVFVNNGQwMTZZM1pPYWtrd1RIcEJkMDE2WXpKTmFsRXdUVlJqZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "12",
"titulo": "Seiren",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalF2TUM4d016Y3ZOak13THpBd016YzJNekEyTXpZdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalF2TUM4d016Y3ZOak13THpBd016YzJNekEyTXpZdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

])