myFunction([
{
"display": "01",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9hVGgzVEhwQmVrNTVPREpOZWxsMlRVUkJlazU2V1hwT2FtTTFUMU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9hVGgzVEhwQmVrNTVPREpOZWxsMlRVUkJlazU2V1hwT2FtTTFUMU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk5lVGgzVEhwQmVrNTVPREpOZWxsMlRVUkJlazU2V1hwT2FtZDNUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk5lVGgzVEhwQmVrNTVPREpOZWxsMlRVUkJlazU2V1hwT2FtZDNUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "03",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOek12TUM4d016Y3ZOak0yTHpBd016YzJNelk0TURBdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOek12TUM4d016Y3ZOak0yTHpBd016YzJNelk0TURBdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "04",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODJNell2TURBek56WXpOamd4TlM1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOUzh3THpBek55ODJNell2TURBek56WXpOamd4TlM1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "05",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9RemgzVEhwQmVrNTVPREpOZWxsMlRVUkJlazU2V1hwT2FtZDVUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9RemgzVEhwQmVrNTVPREpOZWxsMlRVUkJlazU2V1hwT2FtZDVUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "06",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy82MzYvMDAzNzYzNjgxNC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy82MzYvMDAzNzYzNjgxNC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "07",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0Ni8wLzAzNy82MzYvMDAzNzYzNjgwMS5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0Ni8wLzAzNy82MzYvMDAzNzYzNjgwMS5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "08",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYXpFeVZGVk5OR1F3TVRaWk0xcFBZV3N3ZVZSSWNFSmtNREUyV1hwS1RtVnNhekJVV0hCV1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYXpFeVZGVk5OR1F3TVRaWk0xcFBZV3N3ZVZSSWNFSmtNREUyV1hwS1RtVnNhekJVV0hCV1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "09",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbFYyVFVNNGQwMTZZM1pPYWsweVRIcEJkMDE2WXpKTmVsazBUa1JyZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbFYyVFVNNGQwMTZZM1pPYWsweVRIcEJkMDE2WXpKTmVsazBUa1JyZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "10",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUmxVd1ZFaHdRbVJyTVVWVVZFNU5aV3hzTmxSdGF6UmtNREZGVkZST1QyRnJNSGxVTUZKT1pWVjRkRTFZWkU5U1JHeDJXV3BPVDAxR1FsaGhSRXBwVmtWVmVsUlZaR3BrVjFKSlZsaFdhMU5HYXprPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUmxVd1ZFaHdRbVJyTVVWVVZFNU5aV3hzTmxSdGF6UmtNREZGVkZST1QyRnJNSGxVTUZKT1pWVjRkRTFZWkU5U1JHeDJXV3BPVDAxR1FsaGhSRXBwVmtWVmVsUlZaR3BrVjFKSlZsaFdhMU5HYXprPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "11",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkVZeVZGVk5OR1F3TVRaWk0xcFBZV3N3ZVZSSWNFSmtNREUyV1hwS1RtVnNhekJVVjNCdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkVZeVZGVk5OR1F3TVRaWk0xcFBZV3N3ZVZSSWNFSmtNREUyV1hwS1RtVnNhekJVVjNCdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "12",
"titulo": "Rakudai Kishi no Cavalry",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRazVsVkdnelZFaHdRbVZyTlRWUFJFcE9aV3hzTWxSVlVrSmxhelUyVjFod1QyRnRZM2RVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRazVsVkdnelZFaHdRbVZyTlRWUFJFcE9aV3hzTWxSVlVrSmxhelUyVjFod1QyRnRZM2RVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
])