myFunction([
{
"display": "01",
"titulo": "Pokemon Sun & Moon",
"subt": "Audio Español",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalF2TUM4d016Y3ZOVEU0THpBd016YzFNVGc1TWpJdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalF2TUM4d016Y3ZOVEU0THpBd016YzFNVGc1TWpJdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "02",
"titulo": "Pokemon Sun & Moon",
"subt": "Audio Español",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha2wyVFVNNGQwMTZZM1pPVkVVMFRIcEJkMDE2WXpGTlZHYzBUMFJyZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha2wyVFVNNGQwMTZZM1pPVkVVMFRIcEJkMDE2WXpGTlZHYzBUMFJyZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},

])