myFunction([
{
"display": "01",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTW0wNU0yTXlMblIxTG5SMkwzWnBaRFl3THpBdk1ETTNMell4TlM4d01ETTNOakUxTkRjeExtMXdORDlvYjNOMFBXaDJiVEUzTUdjdWRIVXVkSFk9K0c='",
"desc": "YUhSMGNEb3ZMMmgyTW0wNU0yTXlMblIxTG5SMkwzWnBaRFl3THpBdk1ETTNMell4TlM4d01ETTNOakUxTkRjeExtMXdORDlvYjNOMFBXaDJiVEUzTUdjdWRIVXVkSFk9K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDE1NS8wLzAzNy82MTUvMDAzNzYxNTQ2Mi5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDE1NS8wLzAzNy82MTUvMDAzNzYxNTQ2Mi5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "03",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTW0wNU0yTXlMblIxTG5SMkwzWnBaREV5TXk4d0x6QXpOeTgyTVRVdk1EQXpOell4TlRRMk5TNXRjRFEvYUc5emREMW9kakU0TWk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyTW0wNU0yTXlMblIxTG5SMkwzWnBaREV5TXk4d0x6QXpOeTgyTVRVdk1EQXpOell4TlRRMk5TNXRjRFEvYUc5emREMW9kakU0TWk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "04",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRmw1VEhwQmRrMUVUVE5NZWxsNFRsTTRkMDFFVFROT2FrVXhUa1JaTWt4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRmw1VEhwQmRrMUVUVE5NZWxsNFRsTTRkMDFFVFROT2FrVXhUa1JaTWt4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "05",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDE1Ni8wLzAzNy82MTUvMDAzNzYxNTUwMy5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDE1Ni8wLzAzNy82MTUvMDAzNzYxNTUwMy5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "06",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDE0My8wLzAzNy82MTUvMDAzNzYxNTUxMC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2Mm05MmMyLnR1LnR2L3ZpZDE0My8wLzAzNy82MTUvMDAzNzYxNTUxMC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "07",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hazEyVFVNNGQwMTZZM1pPYWtVeFRIcEJkMDE2WXpKTlZGVXdUbnBWZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hazEyVFVNNGQwMTZZM1pPYWtVeFRIcEJkMDE2WXpKTlZGVXdUbnBWZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "08",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTF0VFhsTWJsSXhURzVTTWt3elduQmFSRmt3VEhwQmRrMUVUVE5NZWxsNFRsTTRkMDFFVFROT2FrVXhUa1JqZVV4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTF0VFhsTWJsSXhURzVTTWt3elduQmFSRmt3VEhwQmRrMUVUVE5NZWxsNFRsTTRkMDFFVFROT2FrVXhUa1JqZVV4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "09",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE0NS8wLzAzNy82MTUvMDAzNzYxNTQ3Ni5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE0NS8wLzAzNy82MTUvMDAzNzYxNTQ3Ni5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "10",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRmt4VEhwQmRrMUVUVE5NZWxsNFRsTTRkMDFFVFROT2FrVXhUa1JaTkV4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRmt4VEhwQmRrMUVUVE5NZWxsNFRsTTRkMDFFVFROT2FrVXhUa1JaTkV4dE1YZE9SRGx2WWpOT01GQlhhREppVkVVelRVZGpkV1JJVlhWa1NGazkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "11",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9RemgzVEhwQmVrNTVPREpOVkZsMlRVUkJlazU2V1hoT2FsVXpUMU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJUQk9RemgzVEhwQmVrNTVPREpOVkZsMlRVUkJlazU2V1hoT2FsVXpUMU0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "12",
"titulo": "Mahou Shoujo Ikusei Keikaku",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRkJSZW1nelZFaHdRbVZyTlRWUFJFcE9Wa1pzTWxSVlVrSmxhelUyVjFob1QyRnRUak5VTUUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRkJSZW1nelZFaHdRbVZyTlRWUFJFcE9Wa1pzTWxSVlVrSmxhelUyVjFob1QyRnRUak5VTUUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

])