myFunction([
{
"display": "01",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9RemgzVEhwQmVrNTVPREZPZWxsMlRVUkJlazU2VlROT2FtY3hUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9RemgzVEhwQmVrNTVPREZPZWxsMlRVUkJlazU2VlROT2FtY3hUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "02",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkZZeVZGVk5OR1F3TVRaWk0xcFBWa2ROZWxSSWNFSmtNREUyV1hwR1QyVnRUWGhVVjNCeVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkZZeVZGVk5OR1F3TVRaWk0xcFBWa2ROZWxSSWNFSmtNREUyV1hwR1QyVnRUWGhVVjNCeVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "03",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREZPZWxWMlRVUkJlazU2VlROT1ZHdDVUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5la3h1VWpGTWJsSXlURE5hY0ZwRVJURk9VemgzVEhwQmVrNTVPREZPZWxWMlRVUkJlazU2VlROT1ZHdDVUbWsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOZVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "04",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy81NzYvMDAzNzU3NjczOS5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1Ni8wLzAzNy81NzYvMDAzNzU3NjczOS5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "05",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkd3eVZGVk5OR1F3TVRaWk0xcFBWa2ROZWxSSWNFSmtNREUyV1hwR1QyVnRUak5VTUZKV1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkd3eVZGVk5OR1F3TVRaWk0xcFBWa2ROZWxSSWNFSmtNREUyV1hwR1QyVnRUak5VTUZKV1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "06",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha0YyVFVNNGQwMTZZM1pPVkdNelRIcEJkMDE2WXpGT2VtTjNUMVJGZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha0YyVFVNNGQwMTZZM1pPVkdNelRIcEJkMDE2WXpGT2VtTjNUMVJGZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "07",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTcvMC8wMzcvNTc3LzAwMzc1NzcwOTMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNTcvMC8wMzcvNTc3LzAwMzc1NzcwOTMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "08",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjMvMC8wMzcvNTc3LzAwMzc1NzcxMDAubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjMvMC8wMzcvNTc3LzAwMzc1NzcxMDAubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "09",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTBPUzh3THpBek55ODFOemN2TURBek56VTNOekV5T1M1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTBPUzh3THpBek55ODFOemN2TURBek56VTNOekV5T1M1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "10",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjAvMC8wMzcvNTc3LzAwMzc1NzcxMTMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjAvMC8wMzcvNTc3LzAwMzc1NzcxMTMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "11",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODFOemN2TURBek56VTNOekE1TUM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODFOemN2TURBek56VTNOekE1TUM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "12",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyOS8wLzAzNy81NzcvMDAzNzU3NzA4Ni5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyOS8wLzAzNy81NzcvMDAzNzU3NzA4Ni5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "13",
"titulo": "Chuunibyou demo koi ga shitai Ren",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbGwyVFVNNGQwMTZZM1pPVkdNelRIcEJkMDE2WXpGT2VtTjRUVlJCZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9hbGwyVFVNNGQwMTZZM1pPVkdNelRIcEJkMDE2WXpGT2VtTjRUVlJCZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},

])