myFunction([
{
"display": "01",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREpOVkdkMlRVUkJlazU2V1hoUFJFa3dUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREpOVkdkMlRVUkJlazU2V1hoUFJFa3dUWGsxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFcE9Wa2RrTWxSVlVrSmxhelUyVjFob1VGSkZhekJVYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFcE9Wa2RrTWxSVlVrSmxhelUyVjFob1VGSkZhekJVYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "03",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkZZeVZGVk5OR1F3TVRaWk0xcFBZV3RWTUZSSWNFSmtNREUyV1hwS1RsWkhaRFpVV0hCV1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYkZZeVZGVk5OR1F3TVRaWk0xcFBZV3RWTUZSSWNFSmtNREUyV1hwS1RsWkhaRFpVV0hCV1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "04",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODJNakV2TURBek56WXlNVFF4TlM1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODJNakV2TURBek56WXlNVFF4TlM1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "05",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYlU0eVZGVk5OR1F3TVRaWk0xcFBZV3RWTUZSSWNFSmtNREUyV1hwS1RsWkhZM2hVVmxKU1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYlU0eVZGVk5OR1F3TVRaWk0xcFBZV3RWTUZSSWNFSmtNREUyV1hwS1RsWkhZM2hVVmxKU1pGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "06",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0My8wLzAzNy82MTgvMDAzNzYxODYyNy5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE0My8wLzAzNy82MTgvMDAzNzYxODYyNy5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "07",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalV2TUM4d016Y3ZOakl3THpBd016YzJNakE1T1RFdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOalV2TUM4d016Y3ZOakl3THpBd016YzJNakE1T1RFdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "08",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODJNVGt2TURBek56WXhPVFF4Tmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODJNVGt2TURBek56WXhPVFF4Tmk1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "09",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjIvMC8wMzcvNjE5LzAwMzc2MTk0MTMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjIvMC8wMzcvNjE5LzAwMzc2MTk0MTMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "10",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9WR2QyVFVNNGQwMTZZM1pPYWtVMVRIcEJkMDE2WXpKTlZHc3dUVlJWZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9WR2QyVFVNNGQwMTZZM1pPYWtVMVRIcEJkMDE2WXpKTlZHc3dUVlJWZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "11",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9WR04yVFVNNGQwMTZZM1pPYWtVMVRIcEJkMDE2WXpKTlZHc3dUVlJuZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9WR04yVFVNNGQwMTZZM1pPYWtVMVRIcEJkMDE2WXpKTlZHc3dUVlJuZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "12",
"titulo": "Fairy Tail Zero",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFcE9Wa2QwTWxSVlVrSmxhelUyVjFob1VGWkdSalJVYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFcE9Wa2QwTWxSVlVrSmxhelUyVjFob1VGWkdSalJVYm1zeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},

])