myFunction([
{
"display": "Pelicula 01",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODFNRGN2TURBek56VXdOelUwTmk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRnekxuUjFMblIyTDNacFpERTFOQzh3THpBek55ODFNRGN2TURBek56VXdOelUwTmk1dGNEUS9hRzl6ZEQxb2RqRTRNeTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "01",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZZMlZHMXJOR1F3ZURaUldIQlBaVlJuZDFSdGNHcGthekZGVVZod1QyVnNSWGxVYm5CR1pVVTVSRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUlhhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZZMlZHMXJOR1F3ZURaUldIQlBaVlJuZDFSdGNHcGthekZGVVZod1QyVnNSWGxVYm5CR1pVVTVSRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUlhhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "02",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTF0VFhsTWJsSXhURzVTTWt3elduQmFSRVY2VG5rNGQweDZRWHBPVXpoNlRucEJkazFFUVhwT1ZFMHpUVVJyTTA1VE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTF0VFhsTWJsSXhURzVTTWt3elduQmFSRVY2VG5rNGQweDZRWHBPVXpoNlRucEJkazFFUVhwT1ZFMHpUVVJyTTA1VE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "03",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk5lVGgzVEhwQmVrNTVPSGxOZWxsMlRVUkJlazU2U1hwT2Fra3lUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk5lVGgzVEhwQmVrNTVPSGxOZWxsMlRVUkJlazU2U1hwT2Fra3lUbE0xZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "04",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyNC8wLzAzNy8yMzYvMDAzNzIzNjI2OS5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEyNC8wLzAzNy8yMzYvMDAzNzIzNjI2OS5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "05",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTW0wNU0yTXlMblIxTG5SMkwzWnBaREV6Tnk4d0x6QXpOUzh6TnpJdk1EQXpOVE0zTWpjd01DNXRjRFEvYUc5emREMW9kakU0TXk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyTW0wNU0yTXlMblIxTG5SMkwzWnBaREV6Tnk4d0x6QXpOUzh6TnpJdk1EQXpOVE0zTWpjd01DNXRjRFEvYUc5emREMW9kakU0TXk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "06",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDEzNy8wLzAzNS8zNzIvMDAzNTM3MjcwOC5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDEzNy8wLzAzNS8zNzIvMDAzNTM3MjcwOC5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "07",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVY2VG5rNGQweDZRWHBPVXpoNlRucFJkazFFUVhwT1ZFMHpUa1JKTkU1RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVY2VG5rNGQweDZRWHBPVXpoNlRucFJkazFFUVhwT1ZFMHpUa1JKTkU1RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "08",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDEzNy8wLzAzNS8zNzQvMDAzNTM3NDMwNC5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2Mm05M2MyLnR1LnR2L3ZpZDEzNy8wLzAzNS8zNzQvMDAzNTM3NDMwNC5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "09",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZZMVZGZHJOR1F3ZURaUldIQlBaVlJvTlZSWWNGcGthekZGVVZod1QyVnJiRFpVYlhCT1RWVXhWRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJYTUhkT1ZUQjVWRmhzVFdKc1NYaFVSelZUVFd0M2VsZHVRbUZTUlZZMVZGZHJOR1F3ZURaUldIQlBaVlJvTlZSWWNGcGthekZGVVZod1QyVnJiRFpVYlhCT1RWVXhWRTVZVW1wU1JrVjJXVlZqTldWdFVrVk5WemxyWVd0Vk1GUllhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "10",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVY2VG5rNGQweDZRWHBPVXpoNlRucFJkazFFUVhwT1ZFMHpUa1JOZVU5VE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVY2VG5rNGQweDZRWHBPVXpoNlRucFJkazFFUVhwT1ZFMHpUa1JOZVU5VE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "11",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVV4VGtNNGQweDZRWHBPVXpoNlRucFJkazFFUVhwT1ZFMHpUa1JOTUU1RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTB5VFhsTWJsSXhURzVTTWt3elduQmFSRVV4VGtNNGQweDZRWHBPVXpoNlRucFJkazFFUVhwT1ZFMHpUa1JOTUU1RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRYazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
{
"display": "12",
"titulo": "Date A Live",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRXMHdOVTF0VFhsTWJsSXhURzVTTWt3elduQmFSRVV3VFhrNGQweDZRWHBPVXpoNlRucFJkazFFUVhwT1ZFMHpUa1JOZWs5RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRXazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVRXMHdOVTF0VFhsTWJsSXhURzVTTWt3elduQmFSRVV3VFhrNGQweDZRWHBPVXpoNlRucFJkazFFUVhwT1ZFMHpUa1JOZWs5RE5YUmpSRkV2WVVjNWVtUkVNVzlrYWtVMFRXazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
},
])