myFunction([
{
"display": "Pelicula",
"titulo": "5 Centimetros por segundo",
"subt": "Audio Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXlPQzh3THpBek55ODFPVGN2TURBek56VTVOemswTVM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERXlPQzh3THpBek55ODFPVGN2TURBek56VTVOemswTVM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "img/5centimetros.jpg",
"postervid": "'img/postervid.png'",
},
{
"display": "Pelicula",
"titulo": "El Jardin de las Palabras",
"subt": "Audio Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOamN2TUM4d016Y3ZOVGszTHpBd016YzFPVGM1TlRVdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOamN2TUM4d016Y3ZOVGszTHpBd016YzFPVGM1TlRVdWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "img/jardinpalabras.png",
"postervid": "'img/postervid.png'",
},
{
"display": "Pelicula",
"titulo": "Buda: EL GRAN VIAJE",
"subt": "Audio Esp.",
"url": "'aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjUvMC8wMzcvNTk3LzAwMzc1OTc5NDMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita'",
"desc": "aHR0cDovL2h2bTE3MGcudHUudHYvdmlkNjUvMC8wMzcvNTk3LzAwMzc1OTc5NDMubXA0P2hvc3Q9aHZtMTcwZy50dS50dita",
"onc": "'myVid'",
"imag": "img/budaviaje.jpg",
"postervid": "'img/postervid.png'",
},
{
"display": "Pelicula",
"titulo": "Buda 2 Camino A La Iluminacion",
"subt": "Audio Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazVsVkdnelZFaHdRbVZyTlRWUFJFWlFWa2RPTWxSVlVrSmxhelUyVmxSV1QyVnRjM2RVTUUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazVsVkdnelZFaHdRbVZyTlRWUFJFWlFWa2RPTWxSVlVrSmxhelUyVmxSV1QyVnRjM2RVTUUweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "img/buda2.jpg",
"postervid": "'img/postervid.png'",
},
{
"display": "Pelicula",
"titulo": "La tumba de las luciernagas",
"subt": "Audio Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1My8wLzAzNy81OTcvMDAzNzU5Nzk0OC5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDE1My8wLzAzNy81OTcvMDAzNzU5Nzk0OC5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "img/tumbaluciernaga.jpg",
"postervid": "'img/postervid.png'",
},
{
"display": "Pelicula",
"titulo": "Buddha Saitan",
"subt": "Audio Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjNReVZGVk5OR1F3TVRaWk0xcFBWa2R6ZWxSSWNFSmtNREUyV1hwR1VGWkhUVEZVYm5CYVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTlXUjNReVZGVk5OR1F3TVRaWk0xcFBWa2R6ZWxSSWNFSmtNREUyV1hwR1VGWkhUVEZVYm5CYVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "img/buddasaitan.jpg",
"postervid": "'img/postervid.png'",
},

])