myFunction([
{
"display": "01",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREpOYWtsMlRVUkJlazU2V1hsTmFrMTVUV2sxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU'",
"desc": "WVVoU01HTkViM1pNTW1neVRWUm5lVXh1VWpGTWJsSXlURE5hY0ZwRVJURk9hVGgzVEhwQmVrNTVPREpOYWtsMlRVUkJlazU2V1hsTmFrMTVUV2sxZEdORVVTOWhSemw2WkVReGIyUnFSVFJOYVRVd1pGTTFNR1JuUFQwPStU",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "02",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzMC8wLzAzNy82MjIvMDAzNzYyMjM0OS5tcDQ/aG9zdD1odjE4Mi50dS50dita'",
"desc": "aHR0cDovL2h2MTgyLnR1LnR2L3ZpZDEzMC8wLzAzNy82MjIvMDAzNzYyMjM0OS5tcDQ/aG9zdD1odjE4Mi50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "03",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha0YyVFVNNGQwMTZZM1pPYWtsNVRIcEJkMDE2WXpKTmFrbDZUWHBCZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha0YyVFVNNGQwMTZZM1pPYWtsNVRIcEJkMDE2WXpKTmFrbDZUWHBCZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "04",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRTloVkdnelZFaHdRbVZyTlRWUFJFcE9ZV3RzTWxSVlVrSmxhelUyVjFoc1RtRnJNSGRVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlliRTloVkdnelZFaHdRbVZyTlRWUFJFcE9ZV3RzTWxSVlVrSmxhelUyVjFoc1RtRnJNSGRVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "05",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFcE9ZV3RzTWxSVlVrSmxhelUyVjFoc1RtRnJNVFZVV0dzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVSazloVkdnelZFaHdRbVZyTlRWUFJFcE9ZV3RzTWxSVlVrSmxhelUyVjFoc1RtRnJNVFZVV0dzeFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "06",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRbEJWZW1nelZFaHdRbVZyTlRWUFJFcE9ZV3RzTWxSVlVrSmxhelUyVjFoc1RtRnJNSGhVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y='",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVlJXVW01bFZYaDFWV3BHVFdKc1NYbFVSRTVoWTBad1JWSlVRbEJWZW1nelZFaHdRbVZyTlRWUFJFcE9ZV3RzTWxSVlVrSmxhelUyVjFoc1RtRnJNSGhVVmsweFpFZE9SVlZUT1doU2VtdzJXa1ZSZUdJeVVuRlNWRkpPWVZSVmQxcEdUVEZOUjFKdVVGUXdQUT09K1Y=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "07",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTFZeVZGVk5OR1F3TVRaWk0xcFBZV3RzTlZSSWNFSmtNREUyV1hwS1RtRnJiRFpVYTFKdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW'",
"desc": "V1ZWb1UwMUhUa1ZpTTFwTlRXMW5lVmxzVWtaTk1ERklXVE5XYTFOR1ZqRmFSV2hhWkcxU2RHSkhkRTloYTFZeVZGVk5OR1F3TVRaWk0xcFBZV3RzTlZSSWNFSmtNREUyV1hwS1RtRnJiRFpVYTFKdVpGZEtXVkZVUWxGTmJXZ3lXWHBPVWs5WFJrbFhibEpPVmtkT00xZHVhekZOUjFKVVRsUkNhMXA2TURrPStW",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "08",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NC8wLzAzNy82MjIvMDAzNzYyMjMzOS5tcDQ/aG9zdD1odjE4My50dS50dita'",
"desc": "aHR0cDovL2h2MTgzLnR1LnR2L3ZpZDE1NC8wLzAzNy82MjIvMDAzNzYyMjMzOS5tcDQ/aG9zdD1odjE4My50dS50dita",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "09",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVGt2TUM4d016Y3ZOakl5THpBd016YzJNakl6TWpndWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVGt2TUM4d016Y3ZOakl5THpBd016YzJNakl6TWpndWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "10",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha0YyVFVNNGQwMTZZM1pPYWtsNVRIcEJkMDE2WXpKTmFrbDZUa1JSZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA=='",
"desc": "WVVoU01HTkViM1pNTW1neVlsUkZNMDFIWTNWa1NGVjFaRWhaZG1SdGJHdE9ha0YyVFVNNGQwMTZZM1pPYWtsNVRIcEJkMDE2WXpKTmFrbDZUa1JSZFdKWVFUQlFNbWgyWXpOUk9XRklXblJOVkdOM1duazFNR1JUTlRCa1p6MDkrVA==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "11",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODJNakl2TURBek56WXlNak16TkM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw=='",
"desc": "YUhSMGNEb3ZMMmgyTVRneUxuUjFMblIyTDNacFpERTFOaTh3THpBek55ODJNakl2TURBek56WXlNak16TkM1dGNEUS9hRzl6ZEQxb2RqRTRNaTUwZFM1MGRnPT0rRw==",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
{
"display": "12",
"titulo": "Saijaku Muhai no Bahamut",
"subt": "Sub Esp.",
"url": "'YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVGN2TUM4d016Y3ZOakl5THpBd016YzJNakl6TXpndWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c='",
"desc": "YUhSMGNEb3ZMMmgyYlRFM01HY3VkSFV1ZEhZdmRtbGtOVGN2TUM4d016Y3ZOakl5THpBd016YzJNakl6TXpndWJYQTBQMmh2YzNROWFIWnRNVGN3Wnk1MGRTNTBkZz09K0c=",
"onc": "'myVid'",
"imag": "poster.png",
"postervid": "'img/postervid.png'",
},
])